import type { LevelConfig } from '@/data/types';

export const ESCAPE_LEVELS: LevelConfig[] = [
  {
    id: 'escape_1',
    mode: 'escape',
    levelNumber: 1,
    name: 'Escape The Squares',
    description: 'The viral classic: 6 concentric square boxes with sliding gates and constant velocity!',
    arenaShape: 'nested-boxes',
    arenaSize: 190,
    nestedSquares: [
      { shape: 'square', size: 50, color: 0xa96cff, speed: 0.24, gap: 0.08, openingWidth: 58 },
      { shape: 'square', size: 78, color: 0x49e5b4, speed: -0.20, gap: 0.25, openingWidth: 60 },
      { shape: 'square', size: 106, color: 0xa96cff, speed: 0.18, gap: 0.41, openingWidth: 62 },
      { shape: 'square', size: 134, color: 0xff4848, speed: -0.16, gap: 0.58, openingWidth: 64 },
      { shape: 'square', size: 162, color: 0xd7dce8, speed: 0.14, gap: 0.75, openingWidth: 66 },
      { shape: 'square', size: 190, color: 0xa96cff, speed: -0.12, gap: 0.92, openingWidth: 68 },
    ],
    ballCount: 1,
    obstacles: [],
    objective: {
      type: 'escape_squares',
      targetCount: 6,
      totalSquares: 6,
    },
    stars: {
      oneStar: 6,
      twoStar: 22,
      threeStar: 12,
      criteriaDescription: {
        star1: 'Escape all 6 squares',
        star2: 'Complete in <= 22 seconds',
        star3: 'Complete in <= 12 seconds',
      },
    },
  },
  {
    id: 'escape_2',
    mode: 'escape',
    levelNumber: 2,
    name: 'Escape The Losange',
    description: '6 concentric glowing diamond/losange shapes with alternating perimeter gaps.',
    arenaShape: 'nested-boxes',
    arenaSize: 190,
    nestedSquares: [
      { shape: 'diamond', size: 48, color: 0x00f0ff, speed: 0.22, gap: 0.10, openingWidth: 56 },
      { shape: 'diamond', size: 76, color: 0xa855f7, speed: -0.20, gap: 0.28, openingWidth: 58 },
      { shape: 'diamond', size: 104, color: 0xff007f, speed: 0.18, gap: 0.45, openingWidth: 60 },
      { shape: 'diamond', size: 132, color: 0x00ff88, speed: -0.16, gap: 0.62, openingWidth: 62 },
      { shape: 'diamond', size: 160, color: 0xffe600, speed: 0.14, gap: 0.78, openingWidth: 64 },
      { shape: 'diamond', size: 188, color: 0x00f0ff, speed: -0.12, gap: 0.95, openingWidth: 66 },
    ],
    ballCount: 1,
    obstacles: [],
    objective: {
      type: 'escape_squares',
      targetCount: 6,
      totalSquares: 6,
    },
    stars: {
      oneStar: 6,
      twoStar: 22,
      threeStar: 12,
      criteriaDescription: {
        star1: 'Escape all 6 losanges',
        star2: 'Complete in <= 22 seconds',
        star3: 'Complete in <= 12 seconds',
      },
    },
  },
  {
    id: 'escape_3',
    mode: 'escape',
    levelNumber: 3,
    name: 'Escape The Hearts',
    description: '6 large nested glowing heart enclosures with smoothly orbiting exit windows.',
    arenaShape: 'nested-boxes',
    arenaSize: 225,
    nestedSquares: [
      { shape: 'heart', size: 54, color: 0xff007f, speed: 0.20, gap: 0.05, openingWidth: 56 },
      { shape: 'heart', size: 88, color: 0xff3366, speed: -0.18, gap: 0.22, openingWidth: 58 },
      { shape: 'heart', size: 122, color: 0xff6699, speed: 0.18, gap: 0.38, openingWidth: 60 },
      { shape: 'heart', size: 156, color: 0xff0055, speed: -0.16, gap: 0.55, openingWidth: 62 },
      { shape: 'heart', size: 190, color: 0xef4444, speed: 0.14, gap: 0.72, openingWidth: 64 },
      { shape: 'heart', size: 224, color: 0xff007f, speed: -0.12, gap: 0.88, openingWidth: 66 },
    ],
    ballCount: 1,
    obstacles: [],
    objective: {
      type: 'escape_squares',
      targetCount: 6,
      totalSquares: 6,
    },
    stars: {
      oneStar: 6,
      twoStar: 24,
      threeStar: 14,
      criteriaDescription: {
        star1: 'Escape all 6 hearts',
        star2: 'Complete in <= 24 seconds',
        star3: 'Complete in <= 14 seconds',
      },
    },
  },
  {
    id: 'escape_4',
    mode: 'escape',
    levelNumber: 4,
    name: 'Escape The Hexagons',
    description: '6 concentric neon hexagons with counter-traveling perimeter gaps.',
    arenaShape: 'nested-boxes',
    arenaSize: 190,
    nestedSquares: [
      { shape: 'hexagon', size: 48, color: 0x00ffcc, speed: 0.24, gap: 0.08, openingWidth: 56 },
      { shape: 'hexagon', size: 76, color: 0x38bdf8, speed: -0.22, gap: 0.25, openingWidth: 58 },
      { shape: 'hexagon', size: 104, color: 0x818cf8, speed: 0.20, gap: 0.42, openingWidth: 60 },
      { shape: 'hexagon', size: 132, color: 0xc084fc, speed: -0.18, gap: 0.58, openingWidth: 62 },
      { shape: 'hexagon', size: 160, color: 0xf472b6, speed: 0.16, gap: 0.75, openingWidth: 64 },
      { shape: 'hexagon', size: 188, color: 0xfacc15, speed: -0.14, gap: 0.92, openingWidth: 66 },
    ],
    ballCount: 1,
    obstacles: [],
    objective: {
      type: 'escape_squares',
      targetCount: 6,
      totalSquares: 6,
    },
    stars: {
      oneStar: 6,
      twoStar: 24,
      threeStar: 14,
      criteriaDescription: {
        star1: 'Escape all 6 hexagons',
        star2: 'Complete in <= 24 seconds',
        star3: 'Complete in <= 14 seconds',
      },
    },
  },
  {
    id: 'escape_5',
    mode: 'escape',
    levelNumber: 5,
    name: 'Escape The Circles',
    description: '6 concentric circular rings with planetary orbiting gates and high elasticity.',
    arenaShape: 'nested-boxes',
    arenaSize: 190,
    nestedSquares: [
      { shape: 'circle', size: 48, color: 0x10b981, speed: 0.26, gap: 0.05, openingWidth: 56 },
      { shape: 'circle', size: 76, color: 0x06b6d4, speed: -0.24, gap: 0.22, openingWidth: 58 },
      { shape: 'circle', size: 104, color: 0x3b82f6, speed: 0.22, gap: 0.40, openingWidth: 60 },
      { shape: 'circle', size: 132, color: 0x8b5cf6, speed: -0.20, gap: 0.58, openingWidth: 62 },
      { shape: 'circle', size: 160, color: 0xec4899, speed: 0.18, gap: 0.76, openingWidth: 64 },
      { shape: 'circle', size: 188, color: 0xf59e0b, speed: -0.16, gap: 0.94, openingWidth: 66 },
    ],
    ballCount: 1,
    obstacles: [],
    objective: {
      type: 'escape_squares',
      targetCount: 6,
      totalSquares: 6,
    },
    stars: {
      oneStar: 6,
      twoStar: 25,
      threeStar: 15,
      criteriaDescription: {
        star1: 'Escape all 6 circles',
        star2: 'Complete in <= 25 seconds',
        star3: 'Complete in <= 15 seconds',
      },
    },
  },
  {
    id: 'escape_6',
    mode: 'escape',
    levelNumber: 6,
    name: 'Escape The Triangles',
    description: '6 concentric neon triangles with counter-orbiting perimeter gates and razor precision!',
    arenaShape: 'nested-boxes',
    arenaSize: 195,
    nestedSquares: [
      { shape: 'triangle', size: 58, color: 0x00f5d4, speed: 0.22, gap: 0.08, openingWidth: 64 },
      { shape: 'triangle', size: 88, color: 0x38bdf8, speed: -0.20, gap: 0.25, openingWidth: 66 },
      { shape: 'triangle', size: 118, color: 0xa855f7, speed: 0.18, gap: 0.42, openingWidth: 68 },
      { shape: 'triangle', size: 148, color: 0xff007f, speed: -0.16, gap: 0.58, openingWidth: 70 },
      { shape: 'triangle', size: 178, color: 0xfacc15, speed: 0.14, gap: 0.75, openingWidth: 72 },
      { shape: 'triangle', size: 208, color: 0xff4848, speed: -0.12, gap: 0.92, openingWidth: 74 },
    ],
    ballCount: 1,
    obstacles: [],
    objective: {
      type: 'escape_squares',
      targetCount: 6,
      totalSquares: 6,
      timeLimit: 40,
    },
    stars: {
      oneStar: 6,
      twoStar: 26,
      threeStar: 16,
      criteriaDescription: {
        star1: 'Escape all 6 triangles',
        star2: 'Complete in <= 26 seconds',
        star3: 'Complete in <= 16 seconds',
      },
    },
  },
];
