import type { LevelConfig } from '@/data/types';

export const IMPACT_LEVELS: LevelConfig[] = [
  {
    id: 'neon-impact_1',
    mode: 'neon-impact',
    levelNumber: 1,
    name: 'Square Impact',
    description: 'Neon square arena with 1 moving perimeter spike. Ball grows and slices music on each impact! Reach 5 impacts.',
    arenaShape: 'square',
    arenaSize: 180,
    arenaColor: 0x34f5ff,
    ballCount: 1,
    spikeCount: 1,
    spikeSpeed: 0.055,
    obstacles: [],
    objective: {
      type: 'touch_walls_impact',
      targetCount: 5,
    },
    stars: {
      oneStar: 5,
      twoStar: 8,
      threeStar: 12,
      criteriaDescription: {
        star1: 'Reach 5 wall impacts',
        star2: 'Reach 8 wall impacts',
        star3: 'Reach 12 wall impacts',
      },
    },
  },
  {
    id: 'neon-impact_2',
    mode: 'neon-impact',
    levelNumber: 2,
    name: 'Diamond Impact',
    description: 'Neon diamond with 1 traveling spike around 4 angled faces. Reach 10 impacts.',
    arenaShape: 'diamond',
    arenaSize: 180,
    arenaColor: 0xa855f7,
    ballCount: 1,
    spikeCount: 1,
    spikeSpeed: 0.065,
    obstacles: [],
    objective: {
      type: 'touch_walls_impact',
      targetCount: 10,
    },
    stars: {
      oneStar: 10,
      twoStar: 15,
      threeStar: 20,
      criteriaDescription: {
        star1: 'Reach 10 wall impacts',
        star2: 'Reach 15 wall impacts',
        star3: 'Reach 20 wall impacts',
      },
    },
  },
  {
    id: 'neon-impact_3',
    mode: 'neon-impact',
    levelNumber: 3,
    name: 'Heart Impact Solo Spike',
    description: 'Neon heart arena with 1 traveling spike triangle. Ball expands dynamically! Reach 15 impacts.',
    arenaShape: 'heart',
    arenaSize: 185,
    arenaColor: 0xff007f,
    ballCount: 1,
    spikeCount: 1,
    spikeSpeed: 0.060,
    obstacles: [],
    objective: {
      type: 'touch_walls_impact',
      targetCount: 15,
    },
    stars: {
      oneStar: 15,
      twoStar: 22,
      threeStar: 30,
      criteriaDescription: {
        star1: 'Reach 15 wall impacts',
        star2: 'Reach 22 wall impacts',
        star3: 'Reach 30 wall impacts',
      },
    },
  },
  {
    id: 'neon-impact_4',
    mode: 'neon-impact',
    levelNumber: 4,
    name: 'Hexagon Impact',
    description: 'Hexagonal neon arena with 2 counter-traveling perimeter spikes. Reach 20 impacts.',
    arenaShape: 'hexagon',
    arenaSize: 180,
    arenaColor: 0x00ffcc,
    ballCount: 1,
    spikeCount: 2,
    spikeSpeed: 0.070,
    obstacles: [],
    objective: {
      type: 'touch_walls_impact',
      targetCount: 20,
    },
    stars: {
      oneStar: 20,
      twoStar: 28,
      threeStar: 38,
      criteriaDescription: {
        star1: 'Reach 20 wall impacts',
        star2: 'Reach 28 wall impacts',
        star3: 'Reach 38 wall impacts',
      },
    },
  },
  {
    id: 'neon-impact_5',
    mode: 'neon-impact',
    levelNumber: 5,
    name: 'Circle Impact Quad Spikes',
    description: 'Circular ring with 3 orbiting perimeter spikes. Dodge hazards and reach 25 impacts.',
    arenaShape: 'circle',
    arenaSize: 180,
    arenaColor: 0xfacc15,
    ballCount: 1,
    spikeCount: 3,
    spikeSpeed: 0.065,
    obstacles: [],
    objective: {
      type: 'touch_walls_impact',
      targetCount: 25,
    },
    stars: {
      oneStar: 25,
      twoStar: 35,
      threeStar: 45,
      criteriaDescription: {
        star1: 'Reach 25 wall impacts',
        star2: 'Reach 35 wall impacts',
        star3: 'Reach 45 wall impacts',
      },
    },
  },
  {
    id: 'neon-impact_6',
    mode: 'neon-impact',
    levelNumber: 6,
    name: 'The Hyper Gauntlet',
    description: 'The master arena with 3 high-speed counter-orbiting spikes. Survive and reach 30 impacts!',
    arenaShape: 'hexagon',
    arenaSize: 185,
    arenaColor: 0xff3366,
    ballCount: 1,
    spikeCount: 3,
    spikeSpeed: 0.085,
    obstacles: [],
    objective: {
      type: 'touch_walls_impact',
      targetCount: 30,
    },
    stars: {
      oneStar: 30,
      twoStar: 42,
      threeStar: 55,
      criteriaDescription: {
        star1: 'Reach 30 wall impacts',
        star2: 'Reach 42 wall impacts',
        star3: 'Reach 55 wall impacts',
      },
    },
  },
];
