import type { LevelConfig } from '@/data/types';

/**
 * 6 handcrafted levels for MARBLE ESCAPE.
 * Circular arena with a rotating exit gap. The player drags left/right to
 * spin a needle through the center and knock marbles out through the gap
 * before the time budget runs out.
 */
export const MARBLE_ESCAPE_LEVELS: LevelConfig[] = [
  {
    id: 'orbit-leap_1',
    mode: 'orbit-leap',
    levelNumber: 1,
    name: 'Sector 01: First Spin',
    description: 'Drag left or right to spin the needle. Knock all 6 marbles out through the glowing gap.',
    arenaShape: 'circle',
    arenaSize: 180,
    arenaColor: 0x00f0ff,
    ballCount: 6,
    arenaOpening: { side: 'angle', angle: -Math.PI / 2, width: 0.24, moves: true, moveSpeed: 0.32 },
    needle: { sensitivity: 0.055, damping: 0.55, maxAngularSpeed: 4.5, color: 0xffd85c },
    obstacles: [],
    objective: { type: 'escape_balls', targetCount: 6, timeLimit: 60 },
    stars: {
      oneStar: 1,
      twoStar: 38,
      threeStar: 25,
      criteriaDescription: {
        star1: 'Escape all 6 marbles',
        star2: 'Complete in under 38s',
        star3: 'Complete in under 25s',
      },
    },
  },
  {
    id: 'orbit-leap_2',
    mode: 'orbit-leap',
    levelNumber: 2,
    name: 'Sector 02: Steady Hand',
    description: 'The gap rotates a little faster now. Time your spin to guide marbles into it.',
    arenaShape: 'circle',
    arenaSize: 185,
    arenaColor: 0x00f0ff,
    ballCount: 8,
    arenaOpening: { side: 'angle', angle: -Math.PI / 2, width: 0.21, moves: true, moveSpeed: 0.44 },
    needle: { sensitivity: 0.055, damping: 0.55, maxAngularSpeed: 5, color: 0xffd85c },
    obstacles: [],
    objective: { type: 'escape_balls', targetCount: 8, timeLimit: 65 },
    stars: {
      oneStar: 1,
      twoStar: 42,
      threeStar: 28,
      criteriaDescription: {
        star1: 'Escape all 8 marbles',
        star2: 'Complete in under 42s',
        star3: 'Complete in under 28s',
      },
    },
  },
  {
    id: 'orbit-leap_3',
    mode: 'orbit-leap',
    levelNumber: 3,
    name: 'Sector 03: Narrow Gate',
    description: 'A tighter gap means precise timing. Spin hard, then let it coast into position.',
    arenaShape: 'circle',
    arenaSize: 190,
    arenaColor: 0xa855f7,
    ballCount: 10,
    arenaOpening: { side: 'angle', angle: -Math.PI / 2, width: 0.16, moves: true, moveSpeed: 0.52 },
    needle: { sensitivity: 0.06, damping: 0.5, maxAngularSpeed: 5.5, color: 0xa855f7 },
    obstacles: [],
    objective: { type: 'escape_balls', targetCount: 10, timeLimit: 70 },
    stars: {
      oneStar: 1,
      twoStar: 48,
      threeStar: 32,
      criteriaDescription: {
        star1: 'Escape all 10 marbles',
        star2: 'Complete in under 48s',
        star3: 'Complete in under 32s',
      },
    },
  },
  {
    id: 'orbit-leap_4',
    mode: 'orbit-leap',
    levelNumber: 4,
    name: 'Sector 04: Crowd Control',
    description: 'Twelve marbles bouncing at once. Keep the needle spinning to clear a path.',
    arenaShape: 'circle',
    arenaSize: 195,
    arenaColor: 0x10b981,
    ballCount: 12,
    arenaOpening: { side: 'angle', angle: -Math.PI / 2, width: 0.19, moves: true, moveSpeed: 0.5 },
    needle: { sensitivity: 0.06, damping: 0.5, maxAngularSpeed: 5.5, color: 0x10b981 },
    obstacles: [],
    objective: { type: 'escape_balls', targetCount: 12, timeLimit: 80 },
    stars: {
      oneStar: 1,
      twoStar: 55,
      threeStar: 37,
      criteriaDescription: {
        star1: 'Escape all 12 marbles',
        star2: 'Complete in under 55s',
        star3: 'Complete in under 37s',
      },
    },
  },
  {
    id: 'orbit-leap_5',
    mode: 'orbit-leap',
    levelNumber: 5,
    name: 'Sector 05: Fast Gate',
    description: 'The gap is whipping around the rim now. Reverse the needle’s spin to catch it in time.',
    arenaShape: 'circle',
    arenaSize: 200,
    arenaColor: 0xff007f,
    ballCount: 14,
    arenaOpening: { side: 'angle', angle: -Math.PI / 2, width: 0.15, moves: true, moveSpeed: 0.75 },
    needle: { sensitivity: 0.065, damping: 0.45, maxAngularSpeed: 6, color: 0xff007f },
    obstacles: [],
    objective: { type: 'escape_balls', targetCount: 14, timeLimit: 90 },
    stars: {
      oneStar: 1,
      twoStar: 62,
      threeStar: 42,
      criteriaDescription: {
        star1: 'Escape all 14 marbles',
        star2: 'Complete in under 62s',
        star3: 'Complete in under 42s',
      },
    },
  },
  {
    id: 'orbit-leap_6',
    mode: 'orbit-leap',
    levelNumber: 6,
    name: 'Sector 06: Needle Master',
    description: 'Sixteen marbles, a razor-thin gap, and no time to waste. Prove you’ve mastered the needle.',
    arenaShape: 'circle',
    arenaSize: 205,
    arenaColor: 0xffe000,
    ballCount: 16,
    arenaOpening: { side: 'angle', angle: -Math.PI / 2, width: 0.13, moves: true, moveSpeed: 0.85 },
    needle: { sensitivity: 0.07, damping: 0.42, maxAngularSpeed: 6.5, color: 0xffe000 },
    obstacles: [],
    objective: { type: 'escape_balls', targetCount: 16, timeLimit: 100 },
    stars: {
      oneStar: 1,
      twoStar: 70,
      threeStar: 48,
      criteriaDescription: {
        star1: 'Escape all 16 marbles',
        star2: 'Complete in under 70s',
        star3: 'Complete in under 48s',
      },
    },
  },
];
