import type { LevelConfig } from '@/data/types';

export const MAZE_LEVELS: LevelConfig[] = [
  {
    id: 'neon-maze_1',
    mode: 'neon-maze',
    levelNumber: 1,
    name: 'Dual Orbit',
    description: 'Enclosed circular arena with 2 rotating neon gates. Navigate past the spinning barriers into the core!',
    arenaShape: 'concentric-rings',
    arenaSize: 180,
    rings: [
      { radiusRatio: 1.0, openingAngle: 0, openingWidth: 0, rotationSpeed: 0, closed: true, color: 0x00f0ff },
      { radiusRatio: 0.68, openingAngle: 0, openingWidth: 0.90, rotationSpeed: 0.70, color: 0xa855f7 },
      { radiusRatio: 0.36, openingAngle: Math.PI, openingWidth: 1.25, rotationSpeed: -0.80, color: 0x00ffcc },
    ],
    ballCount: 1,
    obstacles: [],
    objective: {
      type: 'reach_target_point',
    },
    stars: {
      oneStar: 1,
      twoStar: 14,
      threeStar: 7,
      criteriaDescription: {
        star1: 'Reach the core',
        star2: 'Complete in <= 14 seconds',
        star3: 'Complete in <= 7 seconds',
      },
    },
  },
  {
    id: 'neon-maze_2',
    mode: 'neon-maze',
    levelNumber: 2,
    name: 'Triple Helix',
    description: '3 counter-rotating neon gates with accelerating perimeter velocities. Time your angles with precision.',
    arenaShape: 'concentric-rings',
    arenaSize: 185,
    rings: [
      { radiusRatio: 1.0, openingAngle: 0, openingWidth: 0, rotationSpeed: 0, closed: true, color: 0x00f0ff },
      { radiusRatio: 0.78, openingAngle: 0, openingWidth: 0.80, rotationSpeed: 0.80, color: 0x38bdf8 },
      { radiusRatio: 0.54, openingAngle: Math.PI * 0.7, openingWidth: 0.95, rotationSpeed: -0.90, color: 0xa855f7 },
      { radiusRatio: 0.30, openingAngle: -Math.PI * 0.4, openingWidth: 1.30, rotationSpeed: 1.05, color: 0xff007f },
    ],
    ballCount: 1,
    obstacles: [],
    objective: {
      type: 'reach_target_point',
    },
    stars: {
      oneStar: 1,
      twoStar: 16,
      threeStar: 9,
      criteriaDescription: {
        star1: 'Reach the core',
        star2: 'Complete in <= 16 seconds',
        star3: 'Complete in <= 9 seconds',
      },
    },
  },
  {
    id: 'neon-maze_3',
    mode: 'neon-maze',
    levelNumber: 3,
    name: 'Quad Vortex',
    description: '4 narrow counter-spinning gates. Every layer spins faster than the last.',
    arenaShape: 'concentric-rings',
    arenaSize: 190,
    rings: [
      { radiusRatio: 1.0, openingAngle: 0, openingWidth: 0, rotationSpeed: 0, closed: true, color: 0x00f0ff },
      { radiusRatio: 0.82, openingAngle: 0, openingWidth: 0.75, rotationSpeed: 0.90, color: 0x00ffcc },
      { radiusRatio: 0.64, openingAngle: Math.PI * 0.5, openingWidth: 0.85, rotationSpeed: -1.00, color: 0x38bdf8 },
      { radiusRatio: 0.46, openingAngle: Math.PI * 1.2, openingWidth: 1.05, rotationSpeed: 1.10, color: 0xa855f7 },
      { radiusRatio: 0.28, openingAngle: -Math.PI * 0.6, openingWidth: 1.35, rotationSpeed: -1.20, color: 0xff007f },
    ],
    ballCount: 1,
    obstacles: [],
    objective: {
      type: 'reach_target_point',
    },
    stars: {
      oneStar: 1,
      twoStar: 18,
      threeStar: 10,
      criteriaDescription: {
        star1: 'Reach the core',
        star2: 'Complete in <= 18 seconds',
        star3: 'Complete in <= 10 seconds',
      },
    },
  },
  {
    id: 'neon-maze_4',
    mode: 'neon-maze',
    levelNumber: 4,
    name: 'Penta Hazard',
    description: '5 high-speed concentric rings with an orbiting hazard spike guarding the outer corridor.',
    arenaShape: 'concentric-rings',
    arenaSize: 195,
    rings: [
      { radiusRatio: 1.0, openingAngle: 0, openingWidth: 0, rotationSpeed: 0, closed: true, color: 0x00f0ff },
      { radiusRatio: 0.84, openingAngle: 0, openingWidth: 0.70, rotationSpeed: 1.00, color: 0x00ffcc },
      { radiusRatio: 0.70, openingAngle: Math.PI * 0.6, openingWidth: 0.80, rotationSpeed: -1.10, color: 0x38bdf8 },
      { radiusRatio: 0.56, openingAngle: -Math.PI * 0.4, openingWidth: 0.95, rotationSpeed: 1.20, color: 0xa855f7 },
      { radiusRatio: 0.42, openingAngle: Math.PI * 0.8, openingWidth: 1.10, rotationSpeed: -1.30, color: 0xff007f },
      { radiusRatio: 0.26, openingAngle: -Math.PI * 0.8, openingWidth: 1.40, rotationSpeed: 1.40, color: 0xfacc15 },
    ],
    ballCount: 1,
    obstacles: [],
    objective: {
      type: 'reach_target_point',
    },
    stars: {
      oneStar: 1,
      twoStar: 20,
      threeStar: 12,
      criteriaDescription: {
        star1: 'Reach the core',
        star2: 'Complete in <= 20 seconds',
        star3: 'Complete in <= 12 seconds',
      },
    },
  },
  {
    id: 'neon-maze_5',
    mode: 'neon-maze',
    levelNumber: 5,
    name: 'Hexa Storm',
    description: '6 rapid rings with intense counter-spin and accelerating gates.',
    arenaShape: 'concentric-rings',
    arenaSize: 200,
    rings: [
      { radiusRatio: 1.0, openingAngle: 0, openingWidth: 0, rotationSpeed: 0, closed: true, color: 0x00f0ff },
      { radiusRatio: 0.86, openingAngle: 0, openingWidth: 0.68, rotationSpeed: 1.10, color: 0x00ffcc },
      { radiusRatio: 0.74, openingAngle: Math.PI * 0.4, openingWidth: 0.78, rotationSpeed: -1.20, color: 0x38bdf8 },
      { radiusRatio: 0.62, openingAngle: Math.PI * 0.9, openingWidth: 0.88, rotationSpeed: 1.30, color: 0xa855f7 },
      { radiusRatio: 0.50, openingAngle: -Math.PI * 0.5, openingWidth: 1.00, rotationSpeed: -1.40, color: 0xff007f },
      { radiusRatio: 0.38, openingAngle: Math.PI * 0.3, openingWidth: 1.18, rotationSpeed: 1.50, color: 0xfacc15 },
      { radiusRatio: 0.24, openingAngle: -Math.PI * 0.9, openingWidth: 1.45, rotationSpeed: -1.60, color: 0xff4848 },
    ],
    ballCount: 1,
    obstacles: [],
    objective: {
      type: 'reach_target_point',
    },
    stars: {
      oneStar: 1,
      twoStar: 22,
      threeStar: 13,
      criteriaDescription: {
        star1: 'Reach the core',
        star2: 'Complete in <= 22 seconds',
        star3: 'Complete in <= 13 seconds',
      },
    },
  },
  {
    id: 'neon-maze_6',
    mode: 'neon-maze',
    levelNumber: 6,
    name: 'The Singularity',
    description: '7 razor-thin counter-rotating gates with maximum angular velocity and a strict 25s countdown!',
    arenaShape: 'concentric-rings',
    arenaSize: 205,
    rings: [
      { radiusRatio: 1.0, openingAngle: 0, openingWidth: 0, rotationSpeed: 0, closed: true, color: 0x00f0ff },
      { radiusRatio: 0.88, openingAngle: 0, openingWidth: 0.65, rotationSpeed: 1.25, color: 0x00ffcc },
      { radiusRatio: 0.77, openingAngle: Math.PI * 0.6, openingWidth: 0.72, rotationSpeed: -1.35, color: 0x38bdf8 },
      { radiusRatio: 0.66, openingAngle: Math.PI * 1.2, openingWidth: 0.82, rotationSpeed: 1.45, color: 0x818cf8 },
      { radiusRatio: 0.55, openingAngle: -Math.PI * 0.3, openingWidth: 0.95, rotationSpeed: -1.55, color: 0xa855f7 },
      { radiusRatio: 0.44, openingAngle: Math.PI * 0.4, openingWidth: 1.10, rotationSpeed: 1.65, color: 0xff007f },
      { radiusRatio: 0.33, openingAngle: Math.PI, openingWidth: 1.25, rotationSpeed: -1.75, color: 0xfacc15 },
      { radiusRatio: 0.22, openingAngle: -Math.PI * 0.7, openingWidth: 1.50, rotationSpeed: 1.85, color: 0xff4848 },
    ],
    ballCount: 1,
    obstacles: [],
    objective: {
      type: 'reach_target_point',
      timeLimit: 25,
    },
    stars: {
      oneStar: 1,
      twoStar: 18,
      threeStar: 11,
      criteriaDescription: {
        star1: 'Reach the core',
        star2: 'Complete in <= 18 seconds',
        star3: 'Complete in <= 11 seconds',
      },
    },
  },
];
