import type { LevelConfig } from '@/data/types';

/**
 * 30 Handcrafted, progressive levels for ORBIT Gravity game.
 * Mobile-first vertical coordinate space:
 * x: ~ -0.70 (left) to +0.70 (right)
 * y: ~ -0.80 (top / goal area) to +0.75 (bottom / start area)
 */
export const ORBIT_LEVELS: LevelConfig[] = [
  // ==========================================
  // LEVEL 1: Tutorial — The First Leap
  // ==========================================
  {
    id: 'orbit-leap_1',
    mode: 'orbit-leap',
    levelNumber: 1,
    name: 'Sector 01: The First Leap',
    description: 'Tap anywhere when your ball aligns with the golden goal planet.',
    arenaShape: 'circle',
    arenaSize: 350,
    arenaColor: 0x00f0ff,
    ballCount: 1,
    orbitSpeed: 1.15,
    launchSpeed: 820,
    showAim: true,
    tutorialMessage: 'TAP TO LEAVE ORBIT',
    optimalLaunches: 1,
    orbitPlanets: [
      {
        x: 0.0,
        y: 0.42,
        radius: 18,
        orbitRadius: 65,
        angularSpeed: 1.15,
        direction: 1,
        captureRadius: 90,
        color: 0x00f0ff,
        type: 'start',
        label: 'START',
      },
      {
        x: 0.0,
        y: -0.42,
        radius: 20,
        orbitRadius: 68,
        angularSpeed: 0.9,
        direction: 1,
        captureRadius: 95,
        color: 0xffda67,
        type: 'goal',
        label: 'GOAL',
      },
    ],
    orbitHazards: [],
    obstacles: [],
    objective: { type: 'reach_core', targetCount: 2 },
    stars: {
      oneStar: 1,
      twoStar: 20,
      threeStar: 12,
      criteriaDescription: {
        star1: 'Reach the golden goal',
        star2: 'Complete in under 20s',
        star3: 'Complete with 1 launch in under 12s',
      },
    },
  },

  // ==========================================
  // LEVEL 2: Orbital Relay — Learn Capture
  // ==========================================
  {
    id: 'orbit-leap_2',
    mode: 'orbit-leap',
    levelNumber: 2,
    name: 'Sector 02: Orbital Relay',
    description: 'Leap to the intermediate cyan planet, then time your second launch toward the goal.',
    arenaShape: 'circle',
    arenaSize: 350,
    arenaColor: 0x00f0ff,
    ballCount: 1,
    orbitSpeed: 1.25,
    launchSpeed: 830,
    showAim: true,
    optimalLaunches: 2,
    orbitPlanets: [
      {
        x: -0.38,
        y: 0.48,
        radius: 17,
        orbitRadius: 62,
        angularSpeed: 1.2,
        direction: 1,
        color: 0x00f0ff,
        type: 'start',
        label: 'START',
      },
      {
        x: 0.35,
        y: 0.02,
        radius: 18,
        orbitRadius: 64,
        angularSpeed: 1.2,
        direction: -1,
        color: 0x38bdf8,
        type: 'normal',
        label: '02',
      },
      {
        x: -0.32,
        y: -0.48,
        radius: 20,
        orbitRadius: 65,
        angularSpeed: 1.0,
        direction: 1,
        color: 0xffda67,
        type: 'goal',
        label: 'GOAL',
      },
    ],
    orbitHazards: [],
    obstacles: [],
    objective: { type: 'reach_core', targetCount: 3 },
    stars: {
      oneStar: 1,
      twoStar: 25,
      threeStar: 12,
      criteriaDescription: {
        star1: 'Reach the golden goal',
        star2: 'Complete in under 25s',
        star3: 'Complete with 2 launches in under 12s',
      },
    },
  },

  // ==========================================
  // LEVEL 3: Harmonic Scale — Different Sizes
  // ==========================================
  {
    id: 'orbit-leap_3',
    mode: 'orbit-leap',
    levelNumber: 3,
    name: 'Sector 03: Harmonic Scale',
    description: 'Planets of different sizes and gravitational pull require adapted release anticipation.',
    arenaShape: 'circle',
    arenaSize: 350,
    arenaColor: 0xa855f7,
    ballCount: 1,
    orbitSpeed: 1.3,
    launchSpeed: 840,
    showAim: true,
    optimalLaunches: 2,
    orbitPlanets: [
      {
        x: 0.38,
        y: 0.50,
        radius: 16,
        orbitRadius: 55,
        angularSpeed: 1.35,
        direction: -1,
        color: 0x00f0ff,
        type: 'start',
        label: 'START',
      },
      {
        x: -0.32,
        y: 0.05,
        radius: 26,
        orbitRadius: 82,
        angularSpeed: 1.1,
        direction: 1,
        color: 0xa855f7,
        type: 'normal',
        label: '02',
      },
      {
        x: 0.32,
        y: -0.48,
        radius: 19,
        orbitRadius: 58,
        angularSpeed: 1.15,
        direction: -1,
        color: 0xffda67,
        type: 'goal',
        label: 'GOAL',
      },
    ],
    orbitHazards: [],
    obstacles: [],
    objective: { type: 'reach_core', targetCount: 3 },
    stars: {
      oneStar: 1,
      twoStar: 25,
      threeStar: 13,
      criteriaDescription: {
        star1: 'Reach the golden goal',
        star2: 'Complete in under 25s',
        star3: 'Complete with 2 launches in under 13s',
      },
    },
  },

  // ==========================================
  // LEVEL 4: Variable Frequencies — Different Speeds
  // ==========================================
  {
    id: 'orbit-leap_4',
    mode: 'orbit-leap',
    levelNumber: 4,
    name: 'Sector 04: Fast & Slow',
    description: 'A swift orbital transit followed by a leisurely approach.',
    arenaShape: 'circle',
    arenaSize: 350,
    arenaColor: 0x00ff88,
    ballCount: 1,
    orbitSpeed: 1.4,
    launchSpeed: 850,
    showAim: true,
    optimalLaunches: 2,
    orbitPlanets: [
      {
        x: -0.40,
        y: 0.45,
        radius: 16,
        orbitRadius: 54,
        angularSpeed: 1.75, // fast!
        direction: 1,
        color: 0x00ff88,
        type: 'start',
        label: 'FAST',
      },
      {
        x: 0.36,
        y: 0.05,
        radius: 22,
        orbitRadius: 74,
        angularSpeed: 0.85, // slow
        direction: 1,
        color: 0xa855f7,
        type: 'normal',
        label: 'SLOW',
      },
      {
        x: -0.30,
        y: -0.50,
        radius: 19,
        orbitRadius: 60,
        angularSpeed: 1.2,
        direction: -1,
        color: 0xffda67,
        type: 'goal',
        label: 'GOAL',
      },
    ],
    orbitHazards: [],
    obstacles: [],
    objective: { type: 'reach_core', targetCount: 3 },
    stars: {
      oneStar: 1,
      twoStar: 26,
      threeStar: 13,
      criteriaDescription: {
        star1: 'Reach the golden goal',
        star2: 'Complete in under 26s',
        star3: 'Complete with 2 launches in under 13s',
      },
    },
  },

  // ==========================================
  // LEVEL 5: Counter-Clockwise Inversion
  // ==========================================
  {
    id: 'orbit-leap_5',
    mode: 'orbit-leap',
    levelNumber: 5,
    name: 'Sector 05: Counter-Current',
    description: 'Alternating rotation directions test your tangent prediction.',
    arenaShape: 'circle',
    arenaSize: 350,
    arenaColor: 0xff007f,
    ballCount: 1,
    orbitSpeed: 1.35,
    launchSpeed: 850,
    showAim: true,
    optimalLaunches: 3,
    orbitPlanets: [
      {
        x: 0.0,
        y: 0.55,
        radius: 17,
        orbitRadius: 60,
        angularSpeed: 1.3,
        direction: -1,
        color: 0xff007f,
        type: 'start',
        label: 'START',
      },
      {
        x: -0.42,
        y: 0.15,
        radius: 18,
        orbitRadius: 60,
        angularSpeed: 1.4,
        direction: 1,
        color: 0x38bdf8,
        type: 'normal',
        label: '02',
      },
      {
        x: 0.40,
        y: -0.18,
        radius: 18,
        orbitRadius: 62,
        angularSpeed: 1.3,
        direction: -1,
        color: 0x00ff88,
        type: 'normal',
        label: '03',
      },
      {
        x: -0.15,
        y: -0.58,
        radius: 20,
        orbitRadius: 62,
        angularSpeed: 1.0,
        direction: 1,
        color: 0xffda67,
        type: 'goal',
        label: 'GOAL',
      },
    ],
    orbitHazards: [],
    obstacles: [],
    objective: { type: 'reach_core', targetCount: 4 },
    stars: {
      oneStar: 1,
      twoStar: 28,
      threeStar: 15,
      criteriaDescription: {
        star1: 'Reach the golden goal',
        star2: 'Complete in under 28s',
        star3: 'Complete with 3 launches in under 15s',
      },
    },
  },

  // ==========================================
  // LEVEL 6: First Red Hazard
  // ==========================================
  {
    id: 'orbit-leap_6',
    mode: 'orbit-leap',
    levelNumber: 6,
    name: 'Sector 06: Crimson Threat',
    description: 'A glowing red hazard spike blocks direct transit. Time your arc over it.',
    arenaShape: 'circle',
    arenaSize: 350,
    arenaColor: 0x00f0ff,
    ballCount: 1,
    orbitSpeed: 1.25,
    launchSpeed: 840,
    showAim: true,
    optimalLaunches: 2,
    orbitPlanets: [
      {
        x: -0.40,
        y: 0.48,
        radius: 17,
        orbitRadius: 64,
        angularSpeed: 1.2,
        direction: 1,
        color: 0x00f0ff,
        type: 'start',
        label: 'START',
      },
      {
        x: 0.38,
        y: 0.05,
        radius: 19,
        orbitRadius: 66,
        angularSpeed: 1.2,
        direction: -1,
        color: 0xa855f7,
        type: 'normal',
        label: '02',
      },
      {
        x: -0.35,
        y: -0.48,
        radius: 20,
        orbitRadius: 62,
        angularSpeed: 1.0,
        direction: 1,
        color: 0xffda67,
        type: 'goal',
        label: 'GOAL',
      },
    ],
    orbitHazards: [
      {
        type: 'triangle',
        x: -0.05,
        y: 0.28,
        size: 15,
        rotation: 0,
        rotationSpeed: 0.4,
        movementType: 'rotate',
      },
    ],
    obstacles: [],
    objective: { type: 'reach_core', targetCount: 3 },
    stars: {
      oneStar: 1,
      twoStar: 25,
      threeStar: 12,
      criteriaDescription: {
        star1: 'Reach the golden goal',
        star2: 'Complete in under 25s',
        star3: 'Complete with 2 launches in under 12s',
      },
    },
  },

  // ==========================================
  // LEVEL 7: Twin Spikes
  // ==========================================
  {
    id: 'orbit-leap_7',
    mode: 'orbit-leap',
    levelNumber: 7,
    name: 'Sector 07: Twin Peril',
    description: 'Two red triangle obstacles pinch the launch corridor.',
    arenaShape: 'circle',
    arenaSize: 350,
    arenaColor: 0xa855f7,
    ballCount: 1,
    orbitSpeed: 1.3,
    launchSpeed: 850,
    showAim: true,
    optimalLaunches: 2,
    orbitPlanets: [
      {
        x: 0.38,
        y: 0.48,
        radius: 17,
        orbitRadius: 60,
        angularSpeed: 1.25,
        direction: -1,
        color: 0x00f0ff,
        type: 'start',
        label: 'START',
      },
      {
        x: -0.38,
        y: 0.05,
        radius: 18,
        orbitRadius: 64,
        angularSpeed: 1.3,
        direction: 1,
        color: 0xa855f7,
        type: 'normal',
        label: '02',
      },
      {
        x: 0.35,
        y: -0.48,
        radius: 20,
        orbitRadius: 62,
        angularSpeed: 1.0,
        direction: -1,
        color: 0xffda67,
        type: 'goal',
        label: 'GOAL',
      },
    ],
    orbitHazards: [
      {
        type: 'triangle',
        x: 0.05,
        y: 0.28,
        size: 15,
        rotationSpeed: 0.5,
        movementType: 'rotate',
      },
      {
        type: 'triangle',
        x: -0.05,
        y: -0.22,
        size: 15,
        rotationSpeed: -0.5,
        movementType: 'rotate',
      },
    ],
    obstacles: [],
    objective: { type: 'reach_core', targetCount: 3 },
    stars: {
      oneStar: 1,
      twoStar: 25,
      threeStar: 13,
      criteriaDescription: {
        star1: 'Reach the golden goal',
        star2: 'Complete in under 25s',
        star3: 'Complete with 2 launches in under 13s',
      },
    },
  },

  // ==========================================
  // LEVEL 8: Four-Station Waypoint Loop
  // ==========================================
  {
    id: 'orbit-leap_8',
    mode: 'orbit-leap',
    levelNumber: 8,
    name: 'Sector 08: Quad Route',
    description: 'Thread through three intermediate waypoints to reach the summit core.',
    arenaShape: 'circle',
    arenaSize: 350,
    arenaColor: 0x00ff88,
    ballCount: 1,
    orbitSpeed: 1.3,
    launchSpeed: 840,
    showAim: true,
    optimalLaunches: 3,
    orbitPlanets: [
      {
        x: -0.42,
        y: 0.55,
        radius: 17,
        orbitRadius: 58,
        angularSpeed: 1.3,
        direction: 1,
        color: 0x00f0ff,
        type: 'start',
        label: 'START',
      },
      {
        x: 0.40,
        y: 0.25,
        radius: 17,
        orbitRadius: 56,
        angularSpeed: 1.25,
        direction: -1,
        color: 0x00ff88,
        type: 'normal',
        label: '02',
      },
      {
        x: -0.38,
        y: -0.15,
        radius: 17,
        orbitRadius: 56,
        angularSpeed: 1.3,
        direction: 1,
        color: 0x38bdf8,
        type: 'normal',
        label: '03',
      },
      {
        x: 0.35,
        y: -0.55,
        radius: 20,
        orbitRadius: 60,
        angularSpeed: 1.0,
        direction: -1,
        color: 0xffda67,
        type: 'goal',
        label: 'GOAL',
      },
    ],
    orbitHazards: [
      { type: 'triangle', x: -0.02, y: 0.40, size: 14, rotationSpeed: 0.6, movementType: 'rotate' },
      { type: 'triangle', x: 0.02, y: 0.05, size: 14, rotationSpeed: -0.6, movementType: 'rotate' },
      { type: 'triangle', x: -0.02, y: -0.35, size: 14, rotationSpeed: 0.7, movementType: 'rotate' },
    ],
    obstacles: [],
    objective: { type: 'reach_core', targetCount: 4 },
    stars: {
      oneStar: 1,
      twoStar: 28,
      threeStar: 14,
      criteriaDescription: {
        star1: 'Reach the golden goal',
        star2: 'Complete in under 28s',
        star3: 'Complete with 3 launches in under 14s',
      },
    },
  },

  // ==========================================
  // LEVEL 9: Precision Horizon — Tighter Capture
  // ==========================================
  {
    id: 'orbit-leap_9',
    mode: 'orbit-leap',
    levelNumber: 9,
    name: 'Sector 09: Needle Point',
    description: 'Reduced capture radii demand razor-sharp release timing.',
    arenaShape: 'circle',
    arenaSize: 350,
    arenaColor: 0x38bdf8,
    ballCount: 1,
    orbitSpeed: 1.35,
    launchSpeed: 860,
    showAim: true,
    optimalLaunches: 2,
    orbitPlanets: [
      {
        x: 0.0,
        y: 0.48,
        radius: 15,
        orbitRadius: 52,
        angularSpeed: 1.4,
        direction: 1,
        captureRadius: 68,
        color: 0x38bdf8,
        type: 'start',
        label: 'START',
      },
      {
        x: -0.42,
        y: 0.0,
        radius: 14,
        orbitRadius: 48,
        angularSpeed: 1.5,
        direction: -1,
        captureRadius: 65,
        color: 0xa855f7,
        type: 'normal',
        label: '02',
      },
      {
        x: 0.28,
        y: -0.48,
        radius: 19,
        orbitRadius: 56,
        angularSpeed: 1.1,
        direction: 1,
        captureRadius: 76,
        color: 0xffda67,
        type: 'goal',
        label: 'GOAL',
      },
    ],
    orbitHazards: [
      { type: 'triangle', x: -0.22, y: 0.24, size: 14, rotationSpeed: 0.6, movementType: 'rotate' },
      { type: 'triangle', x: -0.08, y: -0.25, size: 14, rotationSpeed: -0.7, movementType: 'rotate' },
    ],
    obstacles: [],
    objective: { type: 'reach_core', targetCount: 3 },
    stars: {
      oneStar: 1,
      twoStar: 25,
      threeStar: 13,
      criteriaDescription: {
        star1: 'Reach the golden goal',
        star2: 'Complete in under 25s',
        star3: 'Complete with 2 launches in under 13s',
      },
    },
  },

  // ==========================================
  // LEVEL 10: The Moving Obstacle
  // ==========================================
  {
    id: 'orbit-leap_10',
    mode: 'orbit-leap',
    levelNumber: 10,
    name: 'Sector 10: Patrol Sentinel',
    description: 'A crimson hazard actively patrols horizontally across the gap.',
    arenaShape: 'circle',
    arenaSize: 350,
    arenaColor: 0xff007f,
    ballCount: 1,
    orbitSpeed: 1.35,
    launchSpeed: 850,
    showAim: true,
    optimalLaunches: 2,
    orbitPlanets: [
      {
        x: -0.38,
        y: 0.46,
        radius: 17,
        orbitRadius: 62,
        angularSpeed: 1.25,
        direction: 1,
        color: 0x00f0ff,
        type: 'start',
        label: 'START',
      },
      {
        x: 0.36,
        y: 0.02,
        radius: 18,
        orbitRadius: 64,
        angularSpeed: 1.3,
        direction: -1,
        color: 0xff007f,
        type: 'normal',
        label: '02',
      },
      {
        x: -0.35,
        y: -0.48,
        radius: 20,
        orbitRadius: 62,
        angularSpeed: 1.0,
        direction: 1,
        color: 0xffda67,
        type: 'goal',
        label: 'GOAL',
      },
    ],
    orbitHazards: [
      {
        type: 'triangle',
        x: 0.0,
        y: 0.24,
        size: 15,
        rotationSpeed: 0.8,
        movementType: 'patrol',
        patrol: { startX: -0.22, startY: 0.24, endX: 0.22, endY: 0.24, speed: 0.5 },
      },
      {
        type: 'triangle',
        x: 0.0,
        y: -0.24,
        size: 15,
        rotationSpeed: -0.8,
        movementType: 'patrol',
        patrol: { startX: 0.22, startY: -0.24, endX: -0.22, endY: -0.24, speed: 0.5 },
      },
    ],
    obstacles: [],
    objective: { type: 'reach_core', targetCount: 3 },
    stars: {
      oneStar: 1,
      twoStar: 26,
      threeStar: 13,
      criteriaDescription: {
        star1: 'Reach the golden goal',
        star2: 'Complete in under 26s',
        star3: 'Complete with 2 launches in under 13s',
      },
    },
  },

  // ==========================================
  // LEVEL 11: Crossfire
  // ==========================================
  {
    id: 'orbit-leap_11',
    mode: 'orbit-leap',
    levelNumber: 11,
    name: 'Sector 11: Crossfire Alley',
    description: 'Moving patrols crossing trajectories between offset planets.',
    arenaShape: 'circle',
    arenaSize: 350,
    arenaColor: 0x00f0ff,
    ballCount: 1,
    orbitSpeed: 1.4,
    launchSpeed: 860,
    showAim: true,
    optimalLaunches: 3,
    orbitPlanets: [
      { x: 0.38, y: 0.52, radius: 17, orbitRadius: 60, angularSpeed: 1.35, direction: -1, color: 0x00f0ff, type: 'start', label: 'START' },
      { x: -0.38, y: 0.20, radius: 17, orbitRadius: 60, angularSpeed: 1.3, direction: 1, color: 0x38bdf8, type: 'normal', label: '02' },
      { x: 0.38, y: -0.16, radius: 17, orbitRadius: 58, angularSpeed: 1.35, direction: -1, color: 0xa855f7, type: 'normal', label: '03' },
      { x: -0.30, y: -0.54, radius: 20, orbitRadius: 62, angularSpeed: 1.05, direction: 1, color: 0xffda67, type: 'goal', label: 'GOAL' },
    ],
    orbitHazards: [
      { type: 'triangle', x: 0.0, y: 0.36, size: 14, rotationSpeed: 1.0, movementType: 'patrol', patrol: { startX: -0.16, startY: 0.36, endX: 0.16, endY: 0.36, speed: 0.6 } },
      { type: 'triangle', x: 0.0, y: 0.02, size: 14, rotationSpeed: -1.0, movementType: 'patrol', patrol: { startX: 0.16, startY: 0.02, endX: -0.16, endY: 0.02, speed: 0.6 } },
      { type: 'triangle', x: 0.0, y: -0.35, size: 14, rotationSpeed: 1.0, movementType: 'patrol', patrol: { startX: -0.16, startY: -0.35, endX: 0.16, endY: -0.35, speed: 0.6 } },
    ],
    obstacles: [],
    objective: { type: 'reach_core', targetCount: 4 },
    stars: { oneStar: 1, twoStar: 28, threeStar: 15, criteriaDescription: { star1: 'Reach the golden goal', star2: 'Complete in under 28s', star3: 'Complete with 3 launches in under 15s' } },
  },

  // ==========================================
  // LEVEL 12: Void Breach
  // ==========================================
  {
    id: 'orbit-leap_12',
    mode: 'orbit-leap',
    levelNumber: 12,
    name: 'Sector 12: Void Breach',
    description: 'A wide gravitational leap across empty space with a solitary spinning hazard.',
    arenaShape: 'circle',
    arenaSize: 350,
    arenaColor: 0xa855f7,
    ballCount: 1,
    orbitSpeed: 1.45,
    launchSpeed: 890,
    showAim: true,
    optimalLaunches: 2,
    orbitPlanets: [
      { x: -0.42, y: 0.48, radius: 17, orbitRadius: 62, angularSpeed: 1.4, direction: 1, color: 0x00f0ff, type: 'start', label: 'START' },
      { x: 0.42, y: 0.02, radius: 24, orbitRadius: 78, angularSpeed: 1.15, direction: -1, color: 0xa855f7, type: 'normal', label: '02' },
      { x: -0.32, y: -0.52, radius: 20, orbitRadius: 64, angularSpeed: 1.0, direction: 1, color: 0xffda67, type: 'goal', label: 'GOAL' },
    ],
    orbitHazards: [
      { type: 'triangle', x: 0.02, y: 0.25, size: 16, rotationSpeed: 1.2, movementType: 'rotate' },
      { type: 'triangle', x: 0.05, y: -0.26, size: 16, rotationSpeed: -1.2, movementType: 'rotate' },
    ],
    obstacles: [],
    objective: { type: 'reach_core', targetCount: 3 },
    stars: { oneStar: 1, twoStar: 25, threeStar: 12, criteriaDescription: { star1: 'Reach the golden goal', star2: 'Complete in under 25s', star3: 'Complete with 2 launches in under 12s' } },
  },

  // ==========================================
  // LEVEL 13: Neon Triad
  // ==========================================
  {
    id: 'orbit-leap_13',
    mode: 'orbit-leap',
    levelNumber: 13,
    name: 'Sector 13: Neon Triad',
    description: 'Equilateral planet configuration surrounded by three synchronized hazards.',
    arenaShape: 'circle',
    arenaSize: 350,
    arenaColor: 0x00ff88,
    ballCount: 1,
    orbitSpeed: 1.4,
    launchSpeed: 860,
    showAim: true,
    optimalLaunches: 2,
    orbitPlanets: [
      { x: -0.38, y: 0.35, radius: 17, orbitRadius: 62, angularSpeed: 1.35, direction: 1, color: 0x00ff88, type: 'start', label: 'START' },
      { x: 0.38, y: 0.35, radius: 18, orbitRadius: 64, angularSpeed: 1.35, direction: -1, color: 0x38bdf8, type: 'normal', label: '02' },
      { x: 0.0, y: -0.42, radius: 20, orbitRadius: 65, angularSpeed: 1.0, direction: 1, color: 0xffda67, type: 'goal', label: 'GOAL' },
    ],
    orbitHazards: [
      { type: 'triangle', x: 0.0, y: 0.35, size: 15, rotationSpeed: 1.2, movementType: 'rotate' },
      { type: 'triangle', x: -0.22, y: -0.05, size: 14, rotationSpeed: -0.8, movementType: 'rotate' },
      { type: 'triangle', x: 0.22, y: -0.05, size: 14, rotationSpeed: 0.8, movementType: 'rotate' },
    ],
    obstacles: [],
    objective: { type: 'reach_core', targetCount: 3 },
    stars: { oneStar: 1, twoStar: 25, threeStar: 12, criteriaDescription: { star1: 'Reach the golden goal', star2: 'Complete in under 25s', star3: 'Complete with 2 launches in under 12s' } },
  },

  // ==========================================
  // LEVEL 14: Accelerando
  // ==========================================
  {
    id: 'orbit-leap_14',
    mode: 'orbit-leap',
    levelNumber: 14,
    name: 'Sector 14: Accelerando',
    description: 'Successively faster orbital velocities test fast reflexes.',
    arenaShape: 'circle',
    arenaSize: 350,
    arenaColor: 0xff007f,
    ballCount: 1,
    orbitSpeed: 1.5,
    launchSpeed: 870,
    showAim: true,
    optimalLaunches: 3,
    orbitPlanets: [
      { x: 0.40, y: 0.54, radius: 17, orbitRadius: 58, angularSpeed: 1.2, direction: -1, color: 0x00f0ff, type: 'start', label: '1.2x' },
      { x: -0.38, y: 0.20, radius: 16, orbitRadius: 54, angularSpeed: 1.5, direction: 1, color: 0xff007f, type: 'normal', label: '1.5x' },
      { x: 0.38, y: -0.16, radius: 15, orbitRadius: 50, angularSpeed: 1.85, direction: -1, color: 0xa855f7, type: 'normal', label: '1.8x' },
      { x: -0.28, y: -0.55, radius: 20, orbitRadius: 62, angularSpeed: 1.0, direction: 1, color: 0xffda67, type: 'goal', label: 'GOAL' },
    ],
    orbitHazards: [
      { type: 'triangle', x: 0.0, y: 0.37, size: 14, rotationSpeed: 0.9, movementType: 'rotate' },
      { type: 'triangle', x: 0.0, y: 0.02, size: 14, rotationSpeed: -1.2, movementType: 'rotate' },
      { type: 'triangle', x: 0.05, y: -0.36, size: 14, rotationSpeed: 1.5, movementType: 'rotate' },
    ],
    obstacles: [],
    objective: { type: 'reach_core', targetCount: 4 },
    stars: { oneStar: 1, twoStar: 28, threeStar: 14, criteriaDescription: { star1: 'Reach the golden goal', star2: 'Complete in under 28s', star3: 'Complete with 3 launches in under 14s' } },
  },

  // ==========================================
  // LEVEL 15: Dual Sentinels
  // ==========================================
  {
    id: 'orbit-leap_15',
    mode: 'orbit-leap',
    levelNumber: 15,
    name: 'Sector 15: Dual Sentinels',
    description: 'Two opposing patrol obstacles guard the golden core.',
    arenaShape: 'circle',
    arenaSize: 350,
    arenaColor: 0x38bdf8,
    ballCount: 1,
    orbitSpeed: 1.45,
    launchSpeed: 870,
    showAim: true,
    optimalLaunches: 3,
    orbitPlanets: [
      { x: -0.42, y: 0.52, radius: 17, orbitRadius: 60, angularSpeed: 1.35, direction: 1, color: 0x38bdf8, type: 'start', label: 'START' },
      { x: 0.40, y: 0.20, radius: 17, orbitRadius: 58, angularSpeed: 1.3, direction: -1, color: 0x00ff88, type: 'normal', label: '02' },
      { x: -0.38, y: -0.15, radius: 17, orbitRadius: 58, angularSpeed: 1.35, direction: 1, color: 0xa855f7, type: 'normal', label: '03' },
      { x: 0.35, y: -0.55, radius: 20, orbitRadius: 62, angularSpeed: 1.0, direction: -1, color: 0xffda67, type: 'goal', label: 'GOAL' },
    ],
    orbitHazards: [
      { type: 'triangle', x: -0.05, y: 0.36, size: 14, rotationSpeed: 1.0, movementType: 'patrol', patrol: { startX: -0.18, startY: 0.36, endX: 0.18, endY: 0.36, speed: 0.55 } },
      { type: 'triangle', x: 0.05, y: 0.03, size: 14, rotationSpeed: -1.0, movementType: 'patrol', patrol: { startX: 0.18, startY: 0.03, endX: -0.18, endY: 0.03, speed: 0.55 } },
      { type: 'triangle', x: -0.05, y: -0.35, size: 14, rotationSpeed: 1.0, movementType: 'patrol', patrol: { startX: -0.18, startY: -0.35, endX: 0.18, endY: -0.35, speed: 0.6 } },
    ],
    obstacles: [],
    objective: { type: 'reach_core', targetCount: 4 },
    stars: { oneStar: 1, twoStar: 28, threeStar: 14, criteriaDescription: { star1: 'Reach the golden goal', star2: 'Complete in under 28s', star3: 'Complete with 3 launches in under 14s' } },
  },

  // ==========================================
  // LEVEL 16: Moving Planet Drift
  // ==========================================
  {
    id: 'orbit-leap_16',
    mode: 'orbit-leap',
    levelNumber: 16,
    name: 'Sector 16: Orbital Drift',
    description: 'An intermediate planet glides slowly horizontally. Time your leap when it aligns.',
    arenaShape: 'circle',
    arenaSize: 350,
    arenaColor: 0x00f0ff,
    ballCount: 1,
    orbitSpeed: 1.4,
    launchSpeed: 860,
    showAim: true,
    optimalLaunches: 2,
    orbitPlanets: [
      { x: -0.38, y: 0.48, radius: 17, orbitRadius: 62, angularSpeed: 1.25, direction: 1, color: 0x00f0ff, type: 'start', label: 'START' },
      {
        x: 0.0,
        y: 0.02,
        radius: 19,
        orbitRadius: 65,
        angularSpeed: 1.2,
        direction: -1,
        color: 0xa855f7,
        type: 'normal',
        label: 'DRIFT',
        movePath: { startX: -0.28, startY: 0.02, endX: 0.28, endY: 0.02, speed: 0.4 },
      },
      { x: 0.35, y: -0.48, radius: 20, orbitRadius: 62, angularSpeed: 1.0, direction: 1, color: 0xffda67, type: 'goal', label: 'GOAL' },
    ],
    orbitHazards: [
      { type: 'triangle', x: 0.25, y: 0.32, size: 14, rotationSpeed: 0.8, movementType: 'rotate' },
      { type: 'triangle', x: -0.25, y: -0.28, size: 14, rotationSpeed: -0.8, movementType: 'rotate' },
    ],
    obstacles: [],
    objective: { type: 'reach_core', targetCount: 3 },
    stars: { oneStar: 1, twoStar: 26, threeStar: 13, criteriaDescription: { star1: 'Reach the golden goal', star2: 'Complete in under 26s', star3: 'Complete with 2 launches in under 13s' } },
  },

  // ==========================================
  // LEVEL 17: Temporary Orbit Decay
  // ==========================================
  {
    id: 'orbit-leap_17',
    mode: 'orbit-leap',
    levelNumber: 17,
    name: 'Sector 17: Unstable Decay',
    description: 'The purple planet has a decaying orbit that can only hold you for 3 rotations!',
    arenaShape: 'circle',
    arenaSize: 350,
    arenaColor: 0xa855f7,
    ballCount: 1,
    orbitSpeed: 1.45,
    launchSpeed: 870,
    showAim: true,
    optimalLaunches: 2,
    orbitPlanets: [
      { x: -0.40, y: 0.46, radius: 17, orbitRadius: 62, angularSpeed: 1.3, direction: 1, color: 0x00f0ff, type: 'start', label: 'START' },
      { x: 0.36, y: 0.02, radius: 18, orbitRadius: 64, angularSpeed: 1.4, direction: -1, color: 0xa855f7, type: 'temporary', maxRotations: 3, label: '3 LOOPS' },
      { x: -0.32, y: -0.48, radius: 20, orbitRadius: 62, angularSpeed: 1.05, direction: 1, color: 0xffda67, type: 'goal', label: 'GOAL' },
    ],
    orbitHazards: [
      { type: 'triangle', x: -0.05, y: 0.24, size: 15, rotationSpeed: 0.9, movementType: 'rotate' },
      { type: 'triangle', x: 0.02, y: -0.24, size: 15, rotationSpeed: -0.9, movementType: 'rotate' },
    ],
    obstacles: [],
    objective: { type: 'reach_core', targetCount: 3 },
    stars: { oneStar: 1, twoStar: 25, threeStar: 12, criteriaDescription: { star1: 'Reach the golden goal', star2: 'Complete in under 25s', star3: 'Complete with 2 launches in under 12s' } },
  },

  // ==========================================
  // LEVEL 18: Direction Inversion Core
  // ==========================================
  {
    id: 'orbit-leap_18',
    mode: 'orbit-leap',
    levelNumber: 18,
    name: 'Sector 18: Gravity Switch',
    description: 'A gravity-switch node flips your rotational orientation upon capture.',
    arenaShape: 'circle',
    arenaSize: 350,
    arenaColor: 0x00ff88,
    ballCount: 1,
    orbitSpeed: 1.4,
    launchSpeed: 860,
    showAim: true,
    optimalLaunches: 2,
    orbitPlanets: [
      { x: 0.38, y: 0.48, radius: 17, orbitRadius: 60, angularSpeed: 1.3, direction: -1, color: 0x00ff88, type: 'start', label: 'START' },
      { x: -0.36, y: 0.02, radius: 19, orbitRadius: 65, angularSpeed: 1.4, direction: 1, color: 0x38bdf8, type: 'switch', label: 'SWITCH' },
      { x: 0.34, y: -0.48, radius: 20, orbitRadius: 62, angularSpeed: 1.0, direction: -1, color: 0xffda67, type: 'goal', label: 'GOAL' },
    ],
    orbitHazards: [
      { type: 'triangle', x: 0.02, y: 0.25, size: 15, rotationSpeed: 0.9, movementType: 'rotate' },
      { type: 'triangle', x: -0.02, y: -0.23, size: 15, rotationSpeed: -0.9, movementType: 'rotate' },
    ],
    obstacles: [],
    objective: { type: 'reach_core', targetCount: 3 },
    stars: { oneStar: 1, twoStar: 25, threeStar: 12, criteriaDescription: { star1: 'Reach the golden goal', star2: 'Complete in under 25s', star3: 'Complete with 2 launches in under 12s' } },
  },

  // ==========================================
  // LEVEL 19: Dual Decaying Waypoints
  // ==========================================
  {
    id: 'orbit-leap_19',
    mode: 'orbit-leap',
    levelNumber: 19,
    name: 'Sector 19: Fleeting Moons',
    description: 'Two consecutive decaying waypoints. Hesitation will break orbit!',
    arenaShape: 'circle',
    arenaSize: 350,
    arenaColor: 0xff007f,
    ballCount: 1,
    orbitSpeed: 1.5,
    launchSpeed: 870,
    showAim: true,
    optimalLaunches: 3,
    orbitPlanets: [
      { x: -0.42, y: 0.54, radius: 17, orbitRadius: 58, angularSpeed: 1.35, direction: 1, color: 0x00f0ff, type: 'start', label: 'START' },
      { x: 0.40, y: 0.20, radius: 17, orbitRadius: 56, angularSpeed: 1.5, direction: -1, color: 0xff007f, type: 'temporary', maxRotations: 3, label: '3 LOOPS' },
      { x: -0.38, y: -0.16, radius: 17, orbitRadius: 56, angularSpeed: 1.5, direction: 1, color: 0xa855f7, type: 'temporary', maxRotations: 3, label: '3 LOOPS' },
      { x: 0.32, y: -0.56, radius: 20, orbitRadius: 62, angularSpeed: 1.05, direction: -1, color: 0xffda67, type: 'goal', label: 'GOAL' },
    ],
    orbitHazards: [
      { type: 'triangle', x: 0.0, y: 0.37, size: 14, rotationSpeed: 1.1, movementType: 'rotate' },
      { type: 'triangle', x: 0.0, y: 0.02, size: 14, rotationSpeed: -1.1, movementType: 'rotate' },
      { type: 'triangle', x: 0.0, y: -0.36, size: 14, rotationSpeed: 1.1, movementType: 'rotate' },
    ],
    obstacles: [],
    objective: { type: 'reach_core', targetCount: 4 },
    stars: { oneStar: 1, twoStar: 26, threeStar: 13, criteriaDescription: { star1: 'Reach the golden goal', star2: 'Complete in under 26s', star3: 'Complete with 3 launches in under 13s' } },
  },

  // ==========================================
  // LEVEL 20: Ascendant Cruiser
  // ==========================================
  {
    id: 'orbit-leap_20',
    mode: 'orbit-leap',
    levelNumber: 20,
    name: 'Sector 20: Ascendant Cruiser',
    description: 'A vertically drifting planet bridging high and low orbital tiers.',
    arenaShape: 'circle',
    arenaSize: 350,
    arenaColor: 0x38bdf8,
    ballCount: 1,
    orbitSpeed: 1.45,
    launchSpeed: 870,
    showAim: true,
    optimalLaunches: 2,
    orbitPlanets: [
      { x: -0.40, y: 0.50, radius: 17, orbitRadius: 60, angularSpeed: 1.35, direction: 1, color: 0x38bdf8, type: 'start', label: 'START' },
      {
        x: 0.32,
        y: 0.05,
        radius: 20,
        orbitRadius: 66,
        angularSpeed: 1.3,
        direction: -1,
        color: 0x00ff88,
        type: 'normal',
        label: 'CRUISER',
        movePath: { startX: 0.32, startY: 0.20, endX: 0.32, endY: -0.15, speed: 0.4 },
      },
      { x: -0.32, y: -0.50, radius: 20, orbitRadius: 62, angularSpeed: 1.0, direction: 1, color: 0xffda67, type: 'goal', label: 'GOAL' },
    ],
    orbitHazards: [
      { type: 'triangle', x: -0.05, y: 0.25, size: 15, rotationSpeed: 0.9, movementType: 'rotate' },
      { type: 'triangle', x: 0.02, y: -0.25, size: 15, rotationSpeed: -0.9, movementType: 'rotate' },
    ],
    obstacles: [],
    objective: { type: 'reach_core', targetCount: 3 },
    stars: { oneStar: 1, twoStar: 25, threeStar: 12, criteriaDescription: { star1: 'Reach the golden goal', star2: 'Complete in under 25s', star3: 'Complete with 2 launches in under 12s' } },
  },

  // ==========================================
  // LEVEL 21: Orbiting Hazard Shield
  // ==========================================
  {
    id: 'orbit-leap_21',
    mode: 'orbit-leap',
    levelNumber: 21,
    name: 'Sector 21: Shielded Orbit',
    description: 'A crimson spike orbits around the intermediate planet. Coordinate your entry window!',
    arenaShape: 'circle',
    arenaSize: 350,
    arenaColor: 0x00f0ff,
    ballCount: 1,
    orbitSpeed: 1.4,
    launchSpeed: 860,
    showAim: true,
    optimalLaunches: 2,
    orbitPlanets: [
      { x: -0.40, y: 0.48, radius: 17, orbitRadius: 62, angularSpeed: 1.3, direction: 1, color: 0x00f0ff, type: 'start', label: 'START' },
      { x: 0.38, y: 0.02, radius: 19, orbitRadius: 65, angularSpeed: 1.35, direction: -1, color: 0xa855f7, type: 'normal', label: '02' },
      { x: -0.35, y: -0.48, radius: 20, orbitRadius: 62, angularSpeed: 1.05, direction: 1, color: 0xffda67, type: 'goal', label: 'GOAL' },
    ],
    orbitHazards: [
      {
        type: 'triangle',
        x: 0.38,
        y: 0.02,
        size: 15,
        rotationSpeed: 1.5,
        movementType: 'orbit_planet',
        orbitPlanetIndex: 1,
        orbitDistance: 92,
        orbitSpeed: 1.2,
      },
      { type: 'triangle', x: -0.05, y: 0.25, size: 14, rotationSpeed: 0.8, movementType: 'rotate' },
    ],
    obstacles: [],
    objective: { type: 'reach_core', targetCount: 3 },
    stars: { oneStar: 1, twoStar: 26, threeStar: 13, criteriaDescription: { star1: 'Reach the golden goal', star2: 'Complete in under 26s', star3: 'Complete with 2 launches in under 13s' } },
  },

  // ==========================================
  // LEVEL 22: Dual Orbiting Spikes
  // ==========================================
  {
    id: 'orbit-leap_22',
    mode: 'orbit-leap',
    levelNumber: 22,
    name: 'Sector 22: Binary Satellite',
    description: 'Opposing orbital satellites revolve around the central purple junction.',
    arenaShape: 'circle',
    arenaSize: 350,
    arenaColor: 0xa855f7,
    ballCount: 1,
    orbitSpeed: 1.45,
    launchSpeed: 870,
    showAim: true,
    optimalLaunches: 2,
    orbitPlanets: [
      { x: 0.40, y: 0.48, radius: 17, orbitRadius: 60, angularSpeed: 1.35, direction: -1, color: 0x00f0ff, type: 'start', label: 'START' },
      { x: -0.36, y: 0.02, radius: 22, orbitRadius: 72, angularSpeed: 1.2, direction: 1, color: 0xa855f7, type: 'normal', label: '02' },
      { x: 0.34, y: -0.48, radius: 20, orbitRadius: 62, angularSpeed: 1.0, direction: -1, color: 0xffda67, type: 'goal', label: 'GOAL' },
    ],
    orbitHazards: [
      {
        type: 'triangle',
        x: -0.36,
        y: 0.02,
        size: 15,
        rotationSpeed: 1.6,
        movementType: 'orbit_planet',
        orbitPlanetIndex: 1,
        orbitDistance: 100,
        orbitSpeed: 1.1,
      },
      {
        type: 'triangle',
        x: -0.36,
        y: 0.02,
        size: 15,
        rotationSpeed: -1.6,
        movementType: 'orbit_planet',
        orbitPlanetIndex: 1,
        orbitDistance: 100,
        orbitSpeed: -1.1,
      },
    ],
    obstacles: [],
    objective: { type: 'reach_core', targetCount: 3 },
    stars: { oneStar: 1, twoStar: 26, threeStar: 13, criteriaDescription: { star1: 'Reach the golden goal', star2: 'Complete in under 26s', star3: 'Complete with 2 launches in under 13s' } },
  },

  // ==========================================
  // LEVEL 23: The Spinning Ring
  // ==========================================
  {
    id: 'orbit-leap_23',
    mode: 'orbit-leap',
    levelNumber: 23,
    name: 'Sector 23: Ring of Fire',
    description: 'Three orbiting hazards form a spinning defense ring around the waypoint.',
    arenaShape: 'circle',
    arenaSize: 350,
    arenaColor: 0x00ff88,
    ballCount: 1,
    orbitSpeed: 1.45,
    launchSpeed: 870,
    showAim: true,
    optimalLaunches: 2,
    orbitPlanets: [
      { x: -0.38, y: 0.48, radius: 17, orbitRadius: 62, angularSpeed: 1.3, direction: 1, color: 0x00ff88, type: 'start', label: 'START' },
      { x: 0.38, y: 0.02, radius: 20, orbitRadius: 66, angularSpeed: 1.25, direction: -1, color: 0x38bdf8, type: 'normal', label: '02' },
      { x: -0.35, y: -0.48, radius: 20, orbitRadius: 62, angularSpeed: 1.0, direction: 1, color: 0xffda67, type: 'goal', label: 'GOAL' },
    ],
    orbitHazards: [
      {
        type: 'triangle',
        x: 0.38,
        y: 0.02,
        size: 14,
        rotationSpeed: 1.5,
        movementType: 'orbit_planet',
        orbitPlanetIndex: 1,
        orbitDistance: 94,
        orbitSpeed: 0.9,
      },
      { type: 'triangle', x: -0.05, y: 0.25, size: 14, rotationSpeed: 0.8, movementType: 'rotate' },
      { type: 'triangle', x: 0.02, y: -0.25, size: 14, rotationSpeed: -0.8, movementType: 'rotate' },
    ],
    obstacles: [],
    objective: { type: 'reach_core', targetCount: 3 },
    stars: { oneStar: 1, twoStar: 26, threeStar: 13, criteriaDescription: { star1: 'Reach the golden goal', star2: 'Complete in under 26s', star3: 'Complete with 2 launches in under 13s' } },
  },

  // ==========================================
  // LEVEL 24: Satellite Swarm
  // ==========================================
  {
    id: 'orbit-leap_24',
    mode: 'orbit-leap',
    levelNumber: 24,
    name: 'Sector 24: Satellite Swarm',
    description: 'Multiple orbiting hazards across two relay stations.',
    arenaShape: 'circle',
    arenaSize: 350,
    arenaColor: 0xff007f,
    ballCount: 1,
    orbitSpeed: 1.5,
    launchSpeed: 880,
    showAim: true,
    optimalLaunches: 3,
    orbitPlanets: [
      { x: -0.42, y: 0.54, radius: 17, orbitRadius: 58, angularSpeed: 1.35, direction: 1, color: 0x00f0ff, type: 'start', label: 'START' },
      { x: 0.40, y: 0.20, radius: 17, orbitRadius: 56, angularSpeed: 1.4, direction: -1, color: 0xff007f, type: 'normal', label: '02' },
      { x: -0.38, y: -0.16, radius: 17, orbitRadius: 56, angularSpeed: 1.4, direction: 1, color: 0xa855f7, type: 'normal', label: '03' },
      { x: 0.32, y: -0.55, radius: 20, orbitRadius: 62, angularSpeed: 1.0, direction: -1, color: 0xffda67, type: 'goal', label: 'GOAL' },
    ],
    orbitHazards: [
      {
        type: 'triangle',
        x: 0.40,
        y: 0.20,
        size: 14,
        rotationSpeed: 1.4,
        movementType: 'orbit_planet',
        orbitPlanetIndex: 1,
        orbitDistance: 82,
        orbitSpeed: 1.2,
      },
      {
        type: 'triangle',
        x: -0.38,
        y: -0.16,
        size: 14,
        rotationSpeed: -1.4,
        movementType: 'orbit_planet',
        orbitPlanetIndex: 2,
        orbitDistance: 82,
        orbitSpeed: -1.2,
      },
      { type: 'triangle', x: 0.0, y: 0.38, size: 14, rotationSpeed: 1.0, movementType: 'rotate' },
      { type: 'triangle', x: 0.0, y: -0.36, size: 14, rotationSpeed: -1.0, movementType: 'rotate' },
    ],
    obstacles: [],
    objective: { type: 'reach_core', targetCount: 4 },
    stars: { oneStar: 1, twoStar: 28, threeStar: 14, criteriaDescription: { star1: 'Reach the golden goal', star2: 'Complete in under 28s', star3: 'Complete with 3 launches in under 14s' } },
  },

  // ==========================================
  // LEVEL 25: The Golden Satellite
  // ==========================================
  {
    id: 'orbit-leap_25',
    mode: 'orbit-leap',
    levelNumber: 25,
    name: 'Sector 25: Golden Sentry',
    description: 'The Goal planet itself is shielded by an orbiting crimson sentry!',
    arenaShape: 'circle',
    arenaSize: 350,
    arenaColor: 0x38bdf8,
    ballCount: 1,
    orbitSpeed: 1.45,
    launchSpeed: 870,
    showAim: true,
    optimalLaunches: 2,
    orbitPlanets: [
      { x: -0.38, y: 0.48, radius: 17, orbitRadius: 62, angularSpeed: 1.3, direction: 1, color: 0x38bdf8, type: 'start', label: 'START' },
      { x: 0.38, y: 0.02, radius: 19, orbitRadius: 65, angularSpeed: 1.35, direction: -1, color: 0x00ff88, type: 'normal', label: '02' },
      { x: -0.35, y: -0.48, radius: 20, orbitRadius: 62, angularSpeed: 1.0, direction: 1, color: 0xffda67, type: 'goal', label: 'GOAL' },
    ],
    orbitHazards: [
      {
        type: 'triangle',
        x: -0.35,
        y: -0.48,
        size: 15,
        rotationSpeed: 1.6,
        movementType: 'orbit_planet',
        orbitPlanetIndex: 2,
        orbitDistance: 92,
        orbitSpeed: 1.1,
      },
      { type: 'triangle', x: -0.05, y: 0.25, size: 14, rotationSpeed: 0.8, movementType: 'rotate' },
      { type: 'triangle', x: 0.02, y: -0.25, size: 14, rotationSpeed: -0.8, movementType: 'rotate' },
    ],
    obstacles: [],
    objective: { type: 'reach_core', targetCount: 3 },
    stars: { oneStar: 1, twoStar: 26, threeStar: 13, criteriaDescription: { star1: 'Reach the golden goal', star2: 'Complete in under 26s', star3: 'Complete with 2 launches in under 13s' } },
  },

  // ==========================================
  // LEVEL 26: The Spiral Gauntlet
  // ==========================================
  {
    id: 'orbit-leap_26',
    mode: 'orbit-leap',
    levelNumber: 26,
    name: 'Sector 26: Spiral Nexus',
    description: 'A 5-waypoint spiral constellation weaving past synchronized hazards.',
    arenaShape: 'circle',
    arenaSize: 350,
    arenaColor: 0x00f0ff,
    ballCount: 1,
    orbitSpeed: 1.5,
    launchSpeed: 880,
    showAim: true,
    optimalLaunches: 4,
    orbitPlanets: [
      { x: -0.42, y: 0.60, radius: 16, orbitRadius: 54, angularSpeed: 1.35, direction: 1, color: 0x00f0ff, type: 'start', label: 'START' },
      { x: 0.40, y: 0.32, radius: 16, orbitRadius: 52, angularSpeed: 1.4, direction: -1, color: 0x38bdf8, type: 'normal', label: '02' },
      { x: -0.36, y: 0.02, radius: 16, orbitRadius: 52, angularSpeed: 1.45, direction: 1, color: 0xa855f7, type: 'normal', label: '03' },
      { x: 0.38, y: -0.28, radius: 16, orbitRadius: 50, angularSpeed: 1.5, direction: -1, color: 0x00ff88, type: 'normal', label: '04' },
      { x: -0.28, y: -0.62, radius: 20, orbitRadius: 60, angularSpeed: 1.0, direction: 1, color: 0xffda67, type: 'goal', label: 'GOAL' },
    ],
    orbitHazards: [
      { type: 'triangle', x: -0.02, y: 0.46, size: 14, rotationSpeed: 1.1, movementType: 'rotate' },
      { type: 'triangle', x: 0.02, y: 0.17, size: 14, rotationSpeed: -1.1, movementType: 'rotate' },
      { type: 'triangle', x: -0.02, y: -0.13, size: 14, rotationSpeed: 1.2, movementType: 'rotate' },
      { type: 'triangle', x: 0.02, y: -0.45, size: 14, rotationSpeed: -1.2, movementType: 'rotate' },
    ],
    obstacles: [],
    objective: { type: 'reach_core', targetCount: 5 },
    stars: { oneStar: 1, twoStar: 30, threeStar: 16, criteriaDescription: { star1: 'Reach the golden goal', star2: 'Complete in under 30s', star3: 'Complete with 4 launches in under 16s' } },
  },

  // ==========================================
  // LEVEL 27: Kinetic Crossroads
  // ==========================================
  {
    id: 'orbit-leap_27',
    mode: 'orbit-leap',
    levelNumber: 27,
    name: 'Sector 27: Kinetic Crossroads',
    description: 'Drifting planet and moving patrol intersecting at the orbital crossroads.',
    arenaShape: 'circle',
    arenaSize: 350,
    arenaColor: 0xa855f7,
    ballCount: 1,
    orbitSpeed: 1.5,
    launchSpeed: 880,
    showAim: true,
    optimalLaunches: 3,
    orbitPlanets: [
      { x: 0.40, y: 0.54, radius: 17, orbitRadius: 58, angularSpeed: 1.35, direction: -1, color: 0x00f0ff, type: 'start', label: 'START' },
      {
        x: -0.36,
        y: 0.16,
        radius: 18,
        orbitRadius: 58,
        angularSpeed: 1.4,
        direction: 1,
        color: 0xa855f7,
        type: 'normal',
        label: 'DRIFT',
        movePath: { startX: -0.36, startY: 0.26, endX: -0.36, endY: 0.06, speed: 0.35 },
      },
      { x: 0.38, y: -0.18, radius: 18, orbitRadius: 58, angularSpeed: 1.4, direction: -1, color: 0x00ff88, type: 'normal', label: '03' },
      { x: -0.30, y: -0.56, radius: 20, orbitRadius: 62, angularSpeed: 1.0, direction: 1, color: 0xffda67, type: 'goal', label: 'GOAL' },
    ],
    orbitHazards: [
      { type: 'triangle', x: 0.0, y: 0.35, size: 15, rotationSpeed: 1.0, movementType: 'patrol', patrol: { startX: -0.16, startY: 0.35, endX: 0.16, endY: 0.35, speed: 0.6 } },
      { type: 'triangle', x: 0.0, y: -0.01, size: 15, rotationSpeed: -1.0, movementType: 'patrol', patrol: { startX: 0.16, startY: -0.01, endX: -0.16, endY: -0.01, speed: 0.6 } },
      { type: 'triangle', x: 0.0, y: -0.37, size: 15, rotationSpeed: 1.2, movementType: 'rotate' },
    ],
    obstacles: [],
    objective: { type: 'reach_core', targetCount: 4 },
    stars: { oneStar: 1, twoStar: 28, threeStar: 15, criteriaDescription: { star1: 'Reach the golden goal', star2: 'Complete in under 28s', star3: 'Complete with 3 launches in under 15s' } },
  },

  // ==========================================
  // LEVEL 28: Eclipse Protocol
  // ==========================================
  {
    id: 'orbit-leap_28',
    mode: 'orbit-leap',
    levelNumber: 28,
    name: 'Sector 28: Eclipse Protocol',
    description: 'Decaying orbit paired with an orbiting crimson hazard.',
    arenaShape: 'circle',
    arenaSize: 350,
    arenaColor: 0x00ff88,
    ballCount: 1,
    orbitSpeed: 1.55,
    launchSpeed: 890,
    showAim: true,
    optimalLaunches: 3,
    orbitPlanets: [
      { x: -0.42, y: 0.54, radius: 17, orbitRadius: 58, angularSpeed: 1.4, direction: 1, color: 0x00ff88, type: 'start', label: 'START' },
      { x: 0.38, y: 0.20, radius: 18, orbitRadius: 58, angularSpeed: 1.5, direction: -1, color: 0xff007f, type: 'temporary', maxRotations: 3, label: '3 LOOPS' },
      { x: -0.38, y: -0.16, radius: 18, orbitRadius: 58, angularSpeed: 1.45, direction: 1, color: 0x38bdf8, type: 'normal', label: '03' },
      { x: 0.32, y: -0.56, radius: 20, orbitRadius: 62, angularSpeed: 1.0, direction: -1, color: 0xffda67, type: 'goal', label: 'GOAL' },
    ],
    orbitHazards: [
      {
        type: 'triangle',
        x: -0.38,
        y: -0.16,
        size: 15,
        rotationSpeed: 1.6,
        movementType: 'orbit_planet',
        orbitPlanetIndex: 2,
        orbitDistance: 86,
        orbitSpeed: 1.25,
      },
      { type: 'triangle', x: -0.02, y: 0.37, size: 14, rotationSpeed: 1.2, movementType: 'rotate' },
      { type: 'triangle', x: 0.0, y: -0.36, size: 14, rotationSpeed: -1.2, movementType: 'rotate' },
    ],
    obstacles: [],
    objective: { type: 'reach_core', targetCount: 4 },
    stars: { oneStar: 1, twoStar: 28, threeStar: 15, criteriaDescription: { star1: 'Reach the golden goal', star2: 'Complete in under 28s', star3: 'Complete with 3 launches in under 15s' } },
  },

  // ==========================================
  // LEVEL 29: REFERENCE SHOWCASE LEVEL
  // Layout matching Godot reference & prompt Section 29:
  // - Bottom-left: cyan start
  // - Middle-right: large purple planet
  // - Top-left: cyan planet
  // - Top-right: yellow GOAL planet
  // - Red triangles between them
  // Route: START CYAN -> PURPLE -> TOP CYAN -> YELLOW GOAL
  // ==========================================
  {
    id: 'orbit-leap_29',
    mode: 'orbit-leap',
    levelNumber: 29,
    name: 'Sector 29: Quantum Singularity (Reference)',
    description: 'The master reference layout: Bottom-left cyan start, middle-right purple, top-left cyan, and top-right golden goal.',
    arenaShape: 'circle',
    arenaSize: 350,
    arenaColor: 0x00f0ff,
    ballCount: 1,
    orbitSpeed: 1.35,
    launchSpeed: 860,
    showAim: true,
    optimalLaunches: 3,
    orbitPlanets: [
      // 0: Bottom-left Cyan starting planet (Godot: 260, 1460)
      {
        x: -0.48,
        y: 0.52,
        radius: 18,
        orbitRadius: 65,
        angularSpeed: 1.35,
        direction: -1,
        color: 0x00f0ff,
        type: 'start',
        label: 'START',
      },
      // 1: Middle-right Purple planet (Godot: 785, 1100)
      {
        x: 0.46,
        y: 0.16,
        radius: 24,
        orbitRadius: 76,
        angularSpeed: 1.25,
        direction: 1,
        color: 0xa855f7,
        type: 'normal',
        label: '02',
      },
      // 2: Top-left Cyan planet (Godot: 285, 710)
      {
        x: -0.44,
        y: -0.24,
        radius: 18,
        orbitRadius: 64,
        angularSpeed: 1.3,
        direction: -1,
        color: 0x00f0ff,
        type: 'normal',
        label: '03',
      },
      // 3: Top-right Golden Goal planet (Godot: 805, 370)
      {
        x: 0.48,
        y: -0.58,
        radius: 22,
        orbitRadius: 62,
        angularSpeed: 1.0,
        direction: 1,
        color: 0xffda67,
        type: 'goal',
        label: 'GOAL',
      },
    ],
    orbitHazards: [
      // Hazards placed between orbits (Godot: 160, 1110; 930, 1450; 550, 580)
      {
        type: 'triangle',
        x: -0.68,
        y: 0.16,
        size: 15,
        rotationSpeed: 0.7,
        movementType: 'rotate',
      },
      {
        type: 'triangle',
        x: 0.70,
        y: 0.50,
        size: 15,
        rotationSpeed: -0.7,
        movementType: 'rotate',
      },
      {
        type: 'triangle',
        x: 0.02,
        y: -0.38,
        size: 15,
        rotationSpeed: 0.8,
        movementType: 'rotate',
      },
      {
        type: 'triangle',
        x: 0.02,
        y: 0.35,
        size: 15,
        rotationSpeed: -0.8,
        movementType: 'rotate',
      },
    ],
    obstacles: [],
    objective: { type: 'reach_core', targetCount: 4 },
    stars: {
      oneStar: 1,
      twoStar: 26,
      threeStar: 13,
      criteriaDescription: {
        star1: 'Reach the golden goal',
        star2: 'Complete in under 26s',
        star3: 'Complete with 3 launches in under 13s',
      },
    },
  },

  // ==========================================
  // LEVEL 30: Solar Zenith — The Mini-Final Challenge
  // ==========================================
  {
    id: 'orbit-leap_30',
    mode: 'orbit-leap',
    levelNumber: 30,
    name: 'Sector 30: Solar Zenith',
    description: 'The pinnacle grand orbital gauntlet. Master timing, gravity transitions, and hazard orbits to achieve final ascension.',
    arenaShape: 'circle',
    arenaSize: 350,
    arenaColor: 0xffda67,
    ballCount: 1,
    orbitSpeed: 1.6,
    launchSpeed: 900,
    showAim: true,
    optimalLaunches: 4,
    orbitPlanets: [
      { x: -0.44, y: 0.64, radius: 17, orbitRadius: 56, angularSpeed: 1.4, direction: 1, color: 0x00f0ff, type: 'start', label: 'START' },
      { x: 0.42, y: 0.35, radius: 18, orbitRadius: 56, angularSpeed: 1.5, direction: -1, color: 0xff007f, type: 'normal', label: '02' },
      {
        x: -0.36,
        y: 0.02,
        radius: 20,
        orbitRadius: 64,
        angularSpeed: 1.4,
        direction: 1,
        color: 0xa855f7,
        type: 'normal',
        label: 'DRIFT',
        movePath: { startX: -0.36, startY: 0.10, endX: -0.36, endY: -0.06, speed: 0.3 },
      },
      { x: 0.38, y: -0.30, radius: 17, orbitRadius: 54, angularSpeed: 1.55, direction: -1, color: 0x00ff88, type: 'temporary', maxRotations: 4, label: '4 LOOPS' },
      { x: -0.28, y: -0.66, radius: 22, orbitRadius: 62, angularSpeed: 1.0, direction: 1, color: 0xffda67, type: 'goal', label: 'GOAL' },
    ],
    orbitHazards: [
      {
        type: 'triangle',
        x: 0.42,
        y: 0.35,
        size: 14,
        rotationSpeed: 1.5,
        movementType: 'orbit_planet',
        orbitPlanetIndex: 1,
        orbitDistance: 82,
        orbitSpeed: 1.2,
      },
      { type: 'triangle', x: -0.02, y: 0.50, size: 14, rotationSpeed: 1.2, movementType: 'rotate' },
      { type: 'triangle', x: 0.02, y: 0.18, size: 14, rotationSpeed: -1.2, movementType: 'rotate' },
      { type: 'triangle', x: 0.0, y: -0.15, size: 15, rotationSpeed: 1.0, movementType: 'patrol', patrol: { startX: -0.16, startY: -0.15, endX: 0.16, endY: -0.15, speed: 0.6 } },
      { type: 'triangle', x: 0.05, y: -0.48, size: 14, rotationSpeed: -1.3, movementType: 'rotate' },
    ],
    obstacles: [],
    objective: { type: 'reach_core', targetCount: 5 },
    stars: {
      oneStar: 1,
      twoStar: 32,
      threeStar: 18,
      criteriaDescription: {
        star1: 'Reach the golden goal',
        star2: 'Complete in under 32s',
        star3: 'Complete with 4 launches in under 18s',
      },
    },
  },
];
