import type { LevelConfig } from '@/data/types';

export const SHATTER_LEVELS: LevelConfig[] = [
  {
    id: 'neon-shatter_1',
    mode: 'neon-shatter',
    levelNumber: 1,
    name: 'Neon Grid Spark',
    description: 'Shatter all 16 glowing crystal bricks with kinetic ricochets. Enjoy ASMR glass harmonics!',
    arenaShape: 'square',
    arenaSize: 175,
    arenaColor: 0x00f0ff,
    ballCount: 1,
    obstacles: [],
    objective: {
      type: 'shatter_bricks',
      targetCount: 16,
    },
    stars: {
      oneStar: 16,
      twoStar: 20,
      threeStar: 12,
      criteriaDescription: {
        star1: 'Shatter all 16 bricks',
        star2: 'Complete in <= 20 seconds',
        star3: 'Complete in <= 12 seconds',
      },
    },
  },
  {
    id: 'neon-shatter_2',
    mode: 'neon-shatter',
    levelNumber: 2,
    name: 'Hexagonal Matrix',
    description: 'Hexagonal chamber with 24 crystal nodes. Bank precise ricochets across the angled facets.',
    arenaShape: 'hexagon',
    arenaSize: 180,
    arenaColor: 0xff007f,
    ballCount: 1,
    obstacles: [],
    objective: {
      type: 'shatter_bricks',
      targetCount: 20,
    },
    stars: {
      oneStar: 20,
      twoStar: 22,
      threeStar: 14,
      criteriaDescription: {
        star1: 'Shatter 20 bricks',
        star2: 'Complete in <= 22 seconds',
        star3: 'Complete in <= 14 seconds',
      },
    },
  },
  {
    id: 'neon-shatter_3',
    mode: 'neon-shatter',
    levelNumber: 3,
    name: 'Diamond Cluster',
    description: 'Diamond geometry with armored 2-hit golden bricks guarding the upper apex.',
    arenaShape: 'diamond',
    arenaSize: 185,
    arenaColor: 0xfacc15,
    ballCount: 1,
    obstacles: [],
    objective: {
      type: 'shatter_bricks',
      targetCount: 20,
    },
    stars: {
      oneStar: 20,
      twoStar: 25,
      threeStar: 16,
      criteriaDescription: {
        star1: 'Shatter 20 bricks',
        star2: 'Complete in <= 25 seconds',
        star3: 'Complete in <= 16 seconds',
      },
    },
  },
  {
    id: 'neon-shatter_4',
    mode: 'neon-shatter',
    levelNumber: 4,
    name: 'Pentagon Fortress',
    description: 'Pentagon chamber. Bank satisfying ricochets across the angled neon facets.',
    arenaShape: 'pentagon',
    arenaSize: 190,
    arenaColor: 0xa855f7,
    ballCount: 1,
    obstacles: [],
    objective: {
      type: 'shatter_bricks',
      targetCount: 20,
    },
    stars: {
      oneStar: 20,
      twoStar: 26,
      threeStar: 17,
      criteriaDescription: {
        star1: 'Shatter 20 bricks',
        star2: 'Complete in <= 26 seconds',
        star3: 'Complete in <= 17 seconds',
      },
    },
  },
  {
    id: 'neon-shatter_5',
    mode: 'neon-shatter',
    levelNumber: 5,
    name: 'Rotating Vortex Lattice',
    description: 'Continuously rotating circular arena. Harness centrifugal momentum to smash the brick lattice.',
    arenaShape: 'circle',
    arenaSize: 190,
    arenaColor: 0x35ff38,
    rotationSpeed: 0.40,
    ballCount: 1,
    obstacles: [],
    objective: {
      type: 'shatter_bricks',
      targetCount: 20,
    },
    stars: {
      oneStar: 20,
      twoStar: 28,
      threeStar: 18,
      criteriaDescription: {
        star1: 'Shatter 20 bricks',
        star2: 'Complete in <= 28 seconds',
        star3: 'Complete in <= 18 seconds',
      },
    },
  },
  {
    id: 'neon-shatter_6',
    mode: 'neon-shatter',
    levelNumber: 6,
    name: 'Mega Nexus Supernova',
    description: 'The master trial: Rotating heart arena with crystal bricks and mesmerizing kinetic momentum!',
    arenaShape: 'heart',
    arenaSize: 195,
    arenaColor: 0xff3366,
    rotationSpeed: 0.45,
    ballCount: 1,
    obstacles: [],
    objective: {
      type: 'shatter_bricks',
      targetCount: 20,
      timeLimit: 35,
    },
    stars: {
      oneStar: 20,
      twoStar: 28,
      threeStar: 18,
      criteriaDescription: {
        star1: 'Shatter 20 bricks in 35s',
        star2: 'Complete in <= 28 seconds',
        star3: 'Complete in <= 18 seconds',
      },
    },
  },
];
