import type { LevelConfig } from '@/data/types';

export const SPIKES_LEVELS: LevelConfig[] = [
  {
    id: 'evolution-spikes_1',
    mode: 'evolution-spikes',
    levelNumber: 1,
    name: 'Genesis Spark',
    description: 'Avoid the central stationary spike. Bank 15 rebounds to awaken your Tier 1 Neon Aura!',
    arenaShape: 'square',
    arenaSize: 165,
    arenaColor: 0x10b981,
    ballCount: 1,
    obstacles: [
      {
        id: 'spike_center_1',
        type: 'spike',
        x: 0,
        y: 0,
        size: 16,
      },
    ],
    objective: {
      type: 'survive_rebounds',
      targetCount: 15,
    },
    stars: {
      oneStar: 15,
      twoStar: 22,
      threeStar: 30,
      criteriaDescription: {
        star1: 'Survive 15 rebounds (Tier 1)',
        star2: 'Reach 22 rebounds',
        star3: 'Reach 30 rebounds',
      },
    },
  },
  {
    id: 'evolution-spikes_2',
    mode: 'evolution-spikes',
    levelNumber: 2,
    name: 'Twin Fangs',
    description: 'Two opposing stationary spikes inside a hexagon chamber. Reach 20 rebounds to awaken Tier 2 Plasma Core!',
    arenaShape: 'hexagon',
    arenaSize: 170,
    arenaColor: 0x00f0ff,
    ballCount: 1,
    obstacles: [
      {
        id: 'spike_left',
        type: 'spike',
        x: -55,
        y: 0,
        size: 16,
      },
      {
        id: 'spike_right',
        type: 'spike',
        x: 55,
        y: 0,
        size: 16,
        rotation: Math.PI,
      },
    ],
    objective: {
      type: 'survive_rebounds',
      targetCount: 20,
    },
    stars: {
      oneStar: 20,
      twoStar: 28,
      threeStar: 36,
      criteriaDescription: {
        star1: 'Survive 20 rebounds (Tier 2)',
        star2: 'Reach 28 rebounds',
        star3: 'Reach 36 rebounds',
      },
    },
  },
  {
    id: 'evolution-spikes_3',
    mode: 'evolution-spikes',
    levelNumber: 3,
    name: 'Oscillating Blades',
    description: 'Two kinetic spikes oscillating vertically across the triangular arena. Reach 25 rebounds.',
    arenaShape: 'triangle',
    arenaSize: 175,
    arenaColor: 0xff007f,
    ballCount: 1,
    obstacles: [
      {
        id: 'spike_moving_1',
        type: 'spike',
        x: -45,
        y: -40,
        size: 16,
        movePath: [{ x: -45, y: -50 }, { x: -45, y: 50 }],
        moveSpeed: 75,
      },
      {
        id: 'spike_moving_2',
        type: 'spike',
        x: 45,
        y: 40,
        size: 16,
        movePath: [{ x: 45, y: 50 }, { x: 45, y: -50 }],
        moveSpeed: 75,
      },
    ],
    objective: {
      type: 'survive_rebounds',
      targetCount: 25,
    },
    stars: {
      oneStar: 25,
      twoStar: 34,
      threeStar: 42,
      criteriaDescription: {
        star1: 'Survive 25 rebounds',
        star2: 'Reach 34 rebounds',
        star3: 'Reach 42 rebounds',
      },
    },
  },
  {
    id: 'evolution-spikes_4',
    mode: 'evolution-spikes',
    levelNumber: 4,
    name: 'Crossfire Crucible',
    description: 'Three high-speed rotating spike blades inside a diamond arena. Reach 30 rebounds for Tier 3 Supernova!',
    arenaShape: 'diamond',
    arenaSize: 180,
    arenaColor: 0xfacc15,
    ballCount: 1,
    obstacles: [
      {
        id: 'spike_penta_1',
        type: 'spike',
        x: 0,
        y: -45,
        size: 16,
        rotationSpeed: 1.8,
      },
      {
        id: 'spike_penta_2',
        type: 'spike',
        x: -50,
        y: 35,
        size: 16,
        rotationSpeed: -1.8,
      },
      {
        id: 'spike_penta_3',
        type: 'spike',
        x: 50,
        y: 35,
        size: 16,
        rotationSpeed: 1.8,
      },
    ],
    objective: {
      type: 'survive_rebounds',
      targetCount: 30,
    },
    stars: {
      oneStar: 30,
      twoStar: 40,
      threeStar: 50,
      criteriaDescription: {
        star1: 'Survive 30 rebounds (Supernova)',
        star2: 'Reach 40 rebounds',
        star3: 'Reach 50 rebounds',
      },
    },
  },
  {
    id: 'evolution-spikes_5',
    mode: 'evolution-spikes',
    levelNumber: 5,
    name: 'Rotating Void',
    description: 'The hexagonal arena itself continuously rotates with 4 perimeter hazard spikes. Reach 35 rebounds.',
    arenaShape: 'hexagon',
    arenaSize: 185,
    arenaColor: 0xa855f7,
    rotationSpeed: 0.45,
    ballCount: 1,
    obstacles: [
      { id: 'spike_c1', type: 'spike', x: 0, y: -65, size: 15, rotationSpeed: 1.5 },
      { id: 'spike_c2', type: 'spike', x: 65, y: 0, size: 15, rotationSpeed: -1.5 },
      { id: 'spike_c3', type: 'spike', x: 0, y: 65, size: 15, rotationSpeed: 1.5 },
      { id: 'spike_c4', type: 'spike', x: -65, y: 0, size: 15, rotationSpeed: -1.5 },
    ],
    objective: {
      type: 'survive_rebounds',
      targetCount: 35,
    },
    stars: {
      oneStar: 35,
      twoStar: 45,
      threeStar: 58,
      criteriaDescription: {
        star1: 'Survive 35 rebounds',
        star2: 'Reach 45 rebounds',
        star3: 'Reach 58 rebounds',
      },
    },
  },
  {
    id: 'evolution-spikes_6',
    mode: 'evolution-spikes',
    levelNumber: 6,
    name: 'Supernova Transcendence',
    description: 'The master trial: Rotating heart arena with 4 moving and spinning hazards. Achieve 45 rebounds for total transcendence!',
    arenaShape: 'heart',
    arenaSize: 195,
    arenaColor: 0xff3366,
    rotationSpeed: 0.40,
    ballCount: 1,
    obstacles: [
      {
        id: 'spike_boss_1',
        type: 'spike',
        x: -45,
        y: -20,
        size: 16,
        movePath: [{ x: -55, y: -20 }, { x: -20, y: 40 }, { x: -55, y: -20 }],
        moveSpeed: 90,
      },
      {
        id: 'spike_boss_2',
        type: 'spike',
        x: 45,
        y: -20,
        size: 16,
        movePath: [{ x: 55, y: -20 }, { x: 20, y: 40 }, { x: 55, y: -20 }],
        moveSpeed: 90,
      },
      { id: 'spike_boss_3', type: 'spike', x: 0, y: -50, size: 15, rotationSpeed: 2.2 },
      { id: 'spike_boss_4', type: 'spike', x: 0, y: 40, size: 15, rotationSpeed: -2.2 },
    ],
    objective: {
      type: 'survive_rebounds',
      targetCount: 45,
      timeLimit: 45,
    },
    stars: {
      oneStar: 45,
      twoStar: 55,
      threeStar: 70,
      criteriaDescription: {
        star1: 'Survive 45 rebounds (Master)',
        star2: 'Reach 55 rebounds',
        star3: 'Reach 70 rebounds',
      },
    },
  },
];
